module.exports = {
  "guideTipTitle1": "Organize your home",
  "guideTipDesc1": "Arrange the furniture such as tables and chairs in your home neatly to create space for cleaning. Organize the scattered items on the floor to avoid the device being blocked or stuck",
  "guideTipTitle2": "Arrange the charging dock properly",
  "guideTipDesc2": "Do not leave any obstacles around the charging dock. Tie up the dock's power cord so as to avoid the vacuum-mop from getting caught on the cord.",
  "guideTipTitle3": "Make sure it is well lit indoor",
  "guideTipDesc3": "Keep the area that needs to be cleaned lit, so that the vacuum-mop can clean optimally.",
  "cleaning": "Cleaning",
  "pause": "Paused",
  "waiting": "Standby",
  "charging": "Charging",
  "gocharging": "Returning charge",
  "completedCharge": "Charging completed",
  "localClean": "Partial cleanup",
  "strongModeTip": "The strong setting is suitable for cleaning carpets. When the suction is increased, the noise will slightly increase and the battery life will decrease.",
  "turboModeTip": "The turbo setting is suitable for cleaning long hair carpets. When the suction is increased, the noise will slightly increase and the battery life will decrease.",
  "experimental": "Experimental features",
  "mapsavemode": "Map saving mode",
  "mapsavetip": "After enabling, smart maps will be improved continuously, you can save maps, set virtual walls and restricted areas, etc.",
  "SmartLearning": "Creating smart map…",
  "SmartLearningTip": "After completing several cleanups under different lighting conditions, the map will be saved and can be used for functions such as zoned cleanups and virtual walls.",
  "SmartLearningTip2": "When starting a cleanup, please open all the doors in your home to ensure the integrity of the map.",
  "saveMapTip1": "Please turn off when the vacuum-mop has no cleaning task.",
  "saveMapTip2": "After disabled, the saved map and the related settings will be cleared.",
  "zonedStopTaskMsg": "This operation will interrupt the current task, are you sure to continue?",
  "cleanTip": "End current cleanup, and return to the dock to charge?",
  "customAreaAfterSmartlearning": "After creating a smart map, you can use the zoned cleanup function.",
  "customAreaMsg": "Vacuum-mop will clean up within the zoned area",
  "areaManage": "Area editor",
  "reset": "Reset",
  "renameNoSelect": "Please select one area to rename",
  "resetFail": "Could not reset",
  "restricted_area": "Virtual wall/restricted area",
  "virtualWallPageTips": "Do not rely on restricted areas and virtual walls to isolate dangerous areas.",
  "virtualAreaMsg": "Save the current restricted area and virtual wall settings?",
  "virtualRactCountMsg": "Maximum number of virtual wall or restricted area has been reached",
  "chargerCoveredRect": "Restricted areas cannot cover the area the charging dock is located in.",
  "chargerCoveredLine": "Virtual walls cannot run through the charging dock.",
  "keepSweeperTitle": "Resume cleanup",
  "resetMapTitle": "Cleanup route doesn't match.",
  "resetMapTip2": "It's recommended to reset the map and sweep all areas in well-lit conditions.",
  "reset_map": "Reset map",
  "heapWarnTitle1": "Filter is nearly exhausted",
  "heapWarnMsg1": "The filter is nearly exhausted, please replace it as soon as possible.",
  "heap": "Filter",
  "remain": "Remaining",
  "remainDay": "Remaining service life: Approx. {hour} hours",
  "heapDesc": "The filter is made of polymer fibers to prevent dust from escaping the dust compartment. Over time, it will slowly get blocked and lose its effectiveness. Therefore, it is recommended to replace the filter every {time} operating hours or less.",
  "materialReset": "Reset {name}",
  "buy": "Purchase now",
  "resetHeapMessage": "Has the filter been replaced with a new one?",
  "slidBrushWarnTipTitle1": "Side brush needs to be replaced soon",
  "slidBrushWarnTipMsg1": "The side brush is nearly worn out, please replace it as soon as possible.",
  "slidBrush": "Side brush",
  "slidBrushDesc": "The side brush directs dirt and debris from the corners towards the main brush. Over time, it will wear and tear and lose its effectiveness. Therefore, it is recommended to replace the side brush every {time} operating hours or less.",
  "resetSlidBrushMessage": "Has the side brush been replaced with a new one?",
  "rollingBrushWarnTitle1": "Main brush needs to be replaced soon",
  "rollingBrushWarnMsg1": "The main brush is nearly worn out, please replace it as soon as possible.",
  "rollingBrush": "Main brush",
  "rollingBrushDesc": "The main brush directs dirt and debris into the vacuum-mop's dust compartment. Over time, it will wear and tear and lose its effectiveness. Therefore, it is recommended to replace the main brush every {time} operating hours or less.",
  "resetRollingBrushMessage": "Has the main brush been replaced with a new one?",
  "heapWarnTitle2": "Filter is exhausted",
  "heapWarnMsg2": "The filter is exhausted, please replace it.",
  "slidBrushWarnTipTitle2": "Side brush needs to be replaced",
  "slidBrushWarnTipMsg2": "The side brush is worn out, please replace it.",
  "rollingBrushWarnTitle2": "Main brush needs to be replaced",
  "rollingBrushWarnMsg2": "The main brush is worn out, please replace it.",
  "warnInfoTitle": "Error details",
  "morequestion": "More feedback details",
  "feedback2": "Feedback",
  "setting": "Settings",
  "robotSetting": "Device Settings",
  "timeZone": "Vacuum-mop's time zone",
  "disturbTime": "DND mode",
  "nodistrubTip": "While enabled, the vacuum-mop will not automatically resume cleanups during the specified period. However, scheduled cleanups will still be carried out during the DND period.",
  "timezoneTip1": "You can sync your phone’s time zone with your vacuum-mop, to make sure both are in the same time zone.",
  "timezoneTip2": "* When the vacuum-mop's time zone is inaccurate, scheduled cleanups and DND mode may not work as expected.",
  "syncTimeZone": "Sync now",
  "syncSuccess": "Synchronized successfully",
  "famaleVoice": "Female voice",
  "used": "Current",
  "use": "Use",
  "cleanTiming": "Scheduled setting",
  "noTiming": "No schedules",
  "once": "Once",
  "Monday": "Mon",
  "Tuesday": "Tue",
  "Wednesday": "Wed",
  "Thursday": "Thu",
  "Friday": "Fri",
  "Saturday": "Sat",
  "Sunday": "Sun",
  "workDay": "Working days (Mon - Fri)",
  "weekend": "Weekends",
  "everyDay": "Daily",
  "modeQuiet": "Silent",
  "modeStandard": "Standard",
  "modeMedium": "Strong",
  "modeStrong": "Turbo",
  "low": "Low",
  "middle": "Medium",
  "high": "High",
  "startTime": "Starting time",
  "repeat": "Repeat",
  "cleanMode": "Cleanup mode",
  "waterVolume": "Water level setting",
  "sure": "OK",
  "cancle": "Cancel",
  "deleteMsg": "Delete this schedule",
  "networkTimeout": "Request timed out",
  "timingNumTip": "Max. scheduled cleanups has been reached, unable to add a scheduled cleanup.",
  "cleanLog": "Cleaning history",
  "totalTime": "Total time",
  "totalAreas": "Total area",
  "totalTimes": "Total times",
  "emptyLog": "History is empty",
  "materialTime": "Service schedule",
  "brushExpireDesc": "Replace in about {time} hours",
  "Instructions": "Instructions",
  "otatitle": "Check for firmware updates",
  "otaChecking": "Checking…",
  "currentVersion": "Current version",
  "latestVersion": "Latest version",
  "isLatestVersion": "Current version is the latest",
  "checkVersionFailed": "Could not check for firmware updates",
  "retry": "Try again",
  "updateNow": "Update",
  "updateTip": "Place the vacuum-mop at the charging dock before updating, and make sure the battery level is more than 15%.",
  "upgradeErr": "Could not update",
  "updating": "Updating…",
  "updateTip2": "Updating, do not turn off or use the vacuum-mop before the update is completed.",
  "installing": "Installing update…",
  "installtip": "Installation process requires restarting the vacuum-mop. This may take a while, please be patient.",
  "updatesuccess": "Updated successfully",
  "upgradeErr1": "Could not download firmware",
  "upgradeErr5": "Could not update firmware",
  "upgradeErr8": "Vacuum-mop cannot be updated while not charging",
  "upgradeErr7": "Unable to update while battery level is too low",
  "updateDialogTip": "Firmware update ({count}) available. Update now?",
  "forceTitle": "New firmware version available",
  "productGuide": "Help",
  "deleteDevice": "Delete device",
  "deveiceName": "Device name",
  "deviceShare": "Device sharing",
  "locationManager": "Location management",
  "otaCheck": "Firmware update",
  "addDesktop": "Add Home screen shortcut",
  "feedback": "Feedback",
  "useTerms": "Legal information",
  "licenseTitle": "User Agreement",
  "policyTitle": "Privacy Policy",
  "functionSetting": "Function settings",
  "generalSetting": "General settings",
  "securitySetting": "Security settings",
  "moreSetting": "More settings",
  "locationRobot": "Locate my vacuum-mop",
  "areaEditTip1": "It is recommended to adjust the areas according to the home's actual layout.",
  "areaMerge": "Merge",
  "areaSplit": "Divide",
  "areaEditTip2": "Please select two adjacent areas to merge",
  "selectOneSplit": "Please select one area to divide",
  "livingRoom": "Living Room",
  "bedRoom": "Bedroom",
  "kitchen": "Kitchen",
  "washingRoom": "Bathroom",
  "balcony": "Balcony",
  "disturbTip": "Cannot be the same as the starting time, please set again.",
  "customClean": "Zone",
  "autoClean": "All",
  "undefined": "Mop cleaning",
  "english": "English",
  "addedAreaNum": "\n{count} selected rooms have been added",
  "local": "Partial ",
  "selectAreaClean": "Selected room cleanup",
  "selectArea": "Room",
  "selectAreaAfterSmartlearning": "After creating a smart map, you can use the selected rooms cleanup function.",
  "timezoneTips": "Do you need to synchronize the time zone.",
  "otaSuccess": "Update successfully",
  "savedMapUse": "Please use it on the map saved",
  "GuideKeepSweeperTips": "The vacuum-mop will be recharged automatically when the power is low during cleaning. The vacuum-mop will continue to clean the un-cleaned area after being charged to appropriate power.",
  "nokeepClean": "The vacuum-mop will not resume cleaning in set period of time ",
  "keepSweeperOnpened": "Broken-point resume cleaning has been turned on",
  "nodistrubTipOpened": "Do-not-disturb mode has been turned on",
  "mop": "Mopping ",
  "offline": "Offline",
  "upgrading": "Updating",
  "positioning": "Positioning/Locating",
  "cleaningTime": "Cleaning time",
  "totalArea": "Cleaning area",
  "maploading1": "Remove any hairs tangled on the main brush in time",
  "maploading2": "The vacuum-mop will automatically shut down if left in sleep mode for more than 2 hours.",
  "maploading3": "The filter can be cleaned with water and reinstalled after being dried.",
  "maploading5": "The vacuum-mop will turn on when it is placed directly onto the charging dock.",
  "maploading6": "Remove the cords and toys from floor before use",
  "maploading7": "Please wipe all sensors clean after the vacuum-mop runs for a while",
  "maploading8": "Do not move the vacuum-mop at a long distance during cleaning, it may get lost",
  "dataLoadingErr": "Data loading failed, please exit and try again",
  "noMapChangeModeTips": "Please use it after the map is completed",
  "selectAreaNumMsg": "Cleaning {num} times",
  "emptyMap": "No map",
  "operateFaild": "Operation failed",
  "mergeTipMsg": "After an area is merged, the timing related to that area will be invalid",
  "areaToplimit": "The partition has reached to maximum",
  "splitTipMsg": "After an area is partitioned, the timing related to that area will be invalid",
  "areaNameWithSpeWords": "Area name can not contain special characters",
  "studyRoom": "Study",
  "diningRoom": "Dining hall",
  "corridor": "Corridor",
  "sundryRoom": "Utility room",
  "cloakRoom": "Cloakroom",
  "mettingRoom": "Drawing room",
  "office": "Office",
  "fitnessArea": "Fitness area",
  "leisureArea": "Recreation area",
  "resetAreaMsg": "Map-related settings will also be deleted. Whether to continue?",
  "resetSuccess": "Reset successfully",
  "wifiMap": "Wi-Fi map",
  "mapStrength": "Strong-Weak",
  "virtualLine": "Virtual Wall",
  "cleanVirtualRect": "No-Go Zone",
  "mopVirtualRect": "Mopping No-Go Zone",
  "keepSweeperInfo": "The vacuum-mop will continue to perform unfinished cleaning tasks after be recharged",
  "chargingWatertankTitle": "Remove the water tank before charging",
  "chargingWatertankInfo": "Remove mopping module before recharging. Avoid wet mops moistening the floor.",
  "resetMapTitle2": "Message Details",
  "volume": "Voice and volume",
  "keepSweeperTips": "After being turned on, the vacuum-mop will be recharged automatically when the power is low during cleaning. The vacuum-mop will continue to clean the un-cleaned area after being charged to appropriate power.",
  "carpetCarpet": "Carpet Boost",
  "syncFail": "Sync failed",
  "robotVolume": "vacuum-mop's volume",
  "volumeTip": "Drag the slider to adjust and listen to the vacuum-mop's voice volume",
  "robotVoice": "vacuum-mop's voice",
  "downloading": "Downloading",
  "downloadFail": "Download failed",
  "invalidTiming": "The map changed, and the timing is invalid",
  "cleanScope": "Cleaning Range",
  "drawOrder": "Press on the hot spots of area to draw a vacuum-mop cleaning order according to the successive cleaning requirements.",
  "noSelectAreaTip": "Please select a cleaning area",
  "timingAutoRouteTip": "You have not added a cleaning order, it will be performed in the default order",
  "timingDrawRouteTip": "The vacuum-mop will clean in the order of the drawn path",
  "timingInNoDisturb": "The scheduled cleaning tasks are set up during the do-not-disturb period. Whether to continue?",
  "cleanInfoDetail": "Cleaning details",
  "cleanStatus": "Cleaning Status",
  "complete": "Complete",
  "break": "Break",
  "productUsageGuide": "Product Usage Guide",
  "FAQ": "FAQ",
  "newEnvNewClean": "A new location detected, the vacuum-mop will start a new cleaning task.",
  "moveBackToDock": "Move the vacuum-mop back to the charging dock and the map will then be restored",
  "hotMap": "Heat Map",
  "carpetCarpetTips": "After being turned on, the vacuum-mop will automatically recognize the carpet, turn on the maximum suction, and automatically resume normal suction after leaving the carpet.\n*It is effective after it starts working in a non-carpet area.",
  "customAreaClean": "Zoned cleanup",
  "loading": "Loading data…",
  "fullCleanup": "Full cleanup",
  "msgSwitch": "Notifications switch",
  "start": "Start",
  "end": "End",
  "areaType": "Partition type",
  "usageGuide": "Usage guide",
  "cleanMopReminder": "After turning on, the vacuum-mop will remind to clean the cloth after the set time",
  "SNMismatch": "This model is not supported in current area",
  "startNow": "Start now",
  "cleanTimes": "Cleaning times",
  "mapManage": "Map management",
  "guideDesc1": "After the cleanup is completed, please let the vacuum-mop return to the charging dock automatically. The vacuum-map is unable to learn maps if you manually move it back to the charging dock.",
  "guideDesc2": "In experimental features, you can use the map saving function after enabling Map saving mode.",
  "guideDesc3": "How do I use zoned cleanup and the virtual wall function?",
  "guideDesc4": "Enable Map saving mode in Settings > Experimental features to successfully learn maps, in order to use zoned cleanup and the virtual wall function.",
  "productDetail": "Product Details",
  "productInstructions": "Product Manual",
  "nextStep": "Next Step",
  "nodisturbTips": "Low battery. The robot will return to the dock to recharge automatically. Once the battery is fully charged, the robot will continue the cleanup. In order to ensure a quiet sleep environment, it is recommended to set a non-disturbing time period.",
  "startExper": "Start to experience",
  "timingStart": "Open",
  "noviceStudyTip1": "Quiet Mode is suitable for cleaning in quiet environment, with the least suction noise and the longest battery life",
  "noviceStudyTip2": "Standard Mode is suitable for cleaning in ordinary environment, with less suction noise and long battery life",
  "raterRegulate": "Water Flow Adjustment",
  "studyMopTip1": "Low Water Flow is suitable for wet floor cleaning",
  "studyMopTip2": "Medium Water Flow is suitable for general cleaning",
  "studyMopTip3": "High Water Flow is suitable for dirty floor cleaning",
  "majorFunction": "Main Functions",
  "studyClean": "Cleaning",
  "studyCharge": "Recharging",
  "cleanAvoidTips": "When the robot is working, it automatically avoids the Virtual Wall Zone",
  "restrictedAreaTips": "The robot will not enter this area in the Vacuuming and Mopping Mode",
  "restrictedAreaMopTips": "The Mopping Restricted Area is only for prohibiting the robot from entering the area in Mopping Mode",
  "restrictedAreaClean": "Cleaning the Restricted Area",
  "LineCountTips": "The number of Virtual Walls has reached the limit",
  "cleanRectCountTips": "The number of Cleaning Restricted Area has reached the limit",
  "mopRectCountTips": "The number of Mopping Restricted Areas has reached the limit",
  "save": "Save",
  "noSave": "Don't save",
  "splitErr1": "Division zone is less than 1 square meter; division fails",
  "splitErr2": "The end of the division line is not on the boundary of the division zone; division fails",
  "messageList": "Message Prompt List",
  "messageTips": "Message prompts, please view",
  "faultList": "Fault Prompt List",
  "faultMessageList": "Fault and Message List",
  "faultTips": "Fault prompts, please handle",
  "clothCleanDialog": "Mop cleaning (mopping only)",
  "cleanMin": "{num} minutes later",
  "mapChaged": "Map changed",
  "noComplete": "Unfinished ",
  "selectAreaCountMsg": "Areas selected: {count}"
};