module.exports = {
  "guideTipTitle1": "Organice su casa",
  "guideTipDesc1": "Disponga los muebles como mesas y sillas en su casa de forma ordenada para crear el espacio de limpieza. Organice los elementos dispersos en el suelo para evitar que el dispositivo se bloquee o se atasque",
  "guideTipTitle2": "Disponga la base de carga correctamente",
  "guideTipDesc2": "No deje ningún obstáculo alrededor de la base de carga. Ate el cable de alimentación de la base de carga para evitar que el aspirador con mopa se enganche en el mismo.",
  "guideTipTitle3": "Asegúrese de que el interior esté bien iluminado.",
  "guideTipDesc3": "Mantenga iluminada la zona que debe limpiarse, para que el aspirador con mopa pueda limpiar de forma óptima.",
  "cleaning": "Limpiando...",
  "pause": "Pausado",
  "waiting": "En espera",
  "charging": "Carga",
  "gocharging": "Carga de devolución",
  "completedCharge": "Carga completada",
  "localClean": "Limpieza parcial",
  "strongModeTip": "De construcción reforzada, es adecuado para la limpieza de alfombras. Cuando aumenta la aspiración, aumentará ligeramente el ruido y se reducirá la vida de la batería.",
  "turboModeTip": "La configuración turbo es adecuada para la limpieza de alfombras de pelo largo. Cuando aumenta la aspiración, aumentará ligeramente el ruido y se reducirá la vida de la batería.",
  "experimental": "Características experimentales",
  "mapsavemode": "Modo de ahorro de mapa",
  "mapsavetip": "Después de habilitarlo, los mapas inteligentes se mejorarán continuamente. Podrá guardar mapas, establecer muros virtuales y áreas restringidas, etc.",
  "SmartLearning": "Creando un mapa inteligente..",
  "SmartLearningTip": "Después de completar varias limpiezas bajo diferentes condiciones de iluminación, el mapa se guardará y podrá ser utilizado para funciones como limpiezas por zonas y muros virtuales.",
  "SmartLearningTip2": "Abra todas las puertas de su casa para asegurar la integridad del mapa al iniciar una limpieza.",
  "saveMapTip1": "Apague el aspirador con mopa cuando no tenga tareas de limpieza.",
  "saveMapTip2": "Después de deshabilitarse, el mapa guardado y los ajustes relacionados se eliminarán.",
  "zonedStopTaskMsg": "Esta operación interrumpirá la tarea actual, ¿desea continuar?",
  "cleanTip": "¿Finalizar la limpieza actual y volver al acoplador para cargar?",
  "customAreaAfterSmartlearning": "Después de crear un mapa inteligente, puede utilizar la función de limpieza de zonas.",
  "customAreaMsg": "El aspirador limpiará dentro de la zona indicada",
  "areaManage": "Editor de área",
  "reset": "Restablecer",
  "renameNoSelect": "Seleccione un área para renombrar",
  "resetFail": "No se ha podido restablecer.",
  "restricted_area": "Pared virtual/área restringida",
  "virtualWallPageTips": "No confíe en las áreas restringidas y en las paredes virtuales para aislar las áreas peligrosas.",
  "virtualAreaMsg": "¿Guardar la configuración actual de área restringida y muro virtual?",
  "virtualRactCountMsg": "Se ha alcanzado el número máximo de paredes virtuales o áreas restringidas.",
  "chargerCoveredRect": "Las áreas restringidas no pueden cubrir el área en la que se encuentra la base de carga.",
  "chargerCoveredLine": "Los muros virtuales no pueden atravesar la base de carga.",
  "keepSweeperTitle": "Reanudar la limpieza",
  "resetMapTitle": "La ruta de limpieza no coincide.",
  "resetMapTip2": "Se recomienda reajustar el mapa y barrer todas las áreas en condiciones de buena iluminación.",
  "reset_map": "Reiniciar el mapa",
  "heapWarnTitle1": "El filtro está casi agotado",
  "heapWarnMsg1": "El filtro está casi agotado, reemplácelo lo antes posible.",
  "heap": "Filtro",
  "remain": "Restante",
  "remainDay": "Vida útil restante: Aproximadamente {hour} horas",
  "heapDesc": "El filtro está hecho de fibras de polímero para impedir que el polvo escape del compartimento. Con el tiempo, lentamente se bloqueará, perdiendo su efectividad. Por lo tanto, es recomendable reemplazar el filtro al menos cada {time} horas de funcionamiento.",
  "materialReset": "Restablecer {name}",
  "buy": "Compre ahora",
  "resetHeapMessage": "¿Se ha reemplazado el filtro por uno nuevo?",
  "slidBrushWarnTipTitle1": "El cepillo lateral necesita ser reemplazado pronto",
  "slidBrushWarnTipMsg1": "El cepillo lateral está casi desgastado, reemplácelo lo antes posible.",
  "slidBrush": "Cepillo lateral",
  "slidBrushDesc": "El cepillo lateral dirige suciedad y basura desde las esquinas hacia el cepillo principal. Con el tiempo, se desgastará por el uso y perderá su efectividad. Por lo tanto, es recomendable reemplazar el cepillo lateral al menos cada {time} horas de funcionamiento.",
  "resetSlidBrushMessage": "¿Se ha reemplazado el cepillo lateral por uno nuevo?",
  "rollingBrushWarnTitle1": "El cepillo principal necesita ser reemplazado pronto",
  "rollingBrushWarnMsg1": "El cepillo principal está casi desgastado, reemplácelo lo antes posible.",
  "rollingBrush": "Cepillo principal",
  "rollingBrushDesc": "El cepillo principal dirige suciedad y basura al compartimento de polvo del aspirador. Con el tiempo, se desgastará por el uso y perderá su efectividad. Por lo tanto, es recomendable reemplazar el cepillo principal al menos cada {time} horas de funcionamiento.",
  "resetRollingBrushMessage": "¿Se ha reemplazado el cepillo principal por uno nuevo?",
  "heapWarnTitle2": "El filtro está agotado",
  "heapWarnMsg2": "El filtro está agotado, reemplácelo.",
  "slidBrushWarnTipTitle2": "El cepillo lateral necesita ser reemplazado",
  "slidBrushWarnTipMsg2": "El cepillo lateral está gastado, reemplácelo.",
  "rollingBrushWarnTitle2": "El cepillo principal necesita ser reemplazado",
  "rollingBrushWarnMsg2": "El cepillo principal está gastado, reemplácelo.",
  "warnInfoTitle": "Detalles de error",
  "morequestion": "Más detalles sobre los comentarios",
  "feedback2": "Comentarios",
  "setting": "Ajustes",
  "robotSetting": "Configuración del dispositivo",
  "timeZone": "Zona horaria del aspirador",
  "disturbTime": "Modo DND",
  "nodistrubTip": "Mientras está habilitado, el aspirador no reanudará automáticamente las limpiezas durante el período especificado. Sin embargo, las limpiezas Programadas se llevarán a cabo durante el período DND.",
  "timezoneTip1": "Puede sincronizar la zona horaria de su teléfono con su aspirador, para asegurarse de que ambos estén en la misma zona horaria.",
  "timezoneTip2": "* Cuando la zona horaria del aspirador es inexacta, las limpiezas Programadas y el modo DND (no molestar) pueden no funcionar como se espera.",
  "syncTimeZone": "Sincronizar ahora",
  "syncSuccess": "Sincronizado con éxito",
  "famaleVoice": "Voz femenina",
  "used": "Actual",
  "use": "Uso",
  "cleanTiming": "Ajuste de tiempo",
  "noTiming": "Sin horario programado",
  "once": "Una vez",
  "Monday": "Lun",
  "Tuesday": "Mar",
  "Wednesday": "Mié",
  "Thursday": "Jue",
  "Friday": "Vie",
  "Saturday": "Sáb",
  "Sunday": "Dom",
  "workDay": "Días laborables (lunes a viernes)",
  "weekend": "Fines de semana",
  "everyDay": "Diariamente",
  "modeQuiet": "Silencioso",
  "modeStandard": "Normal",
  "modeMedium": "Fuerte",
  "modeStrong": "Turbo",
  "low": "Baja",
  "middle": "Mediana",
  "high": "Alto",
  "startTime": "Hora de inicio",
  "repeat": "Repetir",
  "cleanMode": "Modo de limpieza",
  "waterVolume": "Ajuste del nivel de agua",
  "sure": "Aceptar",
  "cancle": "Cancelar",
  "deleteMsg": "Borrar esta programación",
  "networkTimeout": "La solicitud ha superado el tiempo de espera",
  "timingNumTip": "Se ha alcanzado el máximo de limpiezas programadas, no se puede calendarizar otra más.",
  "cleanLog": "Historial de limpieza",
  "totalTime": "Tiempo total",
  "totalAreas": "Área total",
  "totalTimes": "Veces totales",
  "emptyLog": "El histórico está vacío",
  "materialTime": "Calendario de servicio",
  "brushExpireDesc": "Reemplazar aproximadamente después de {time} horas",
  "Instructions": "Instrucciones",
  "otatitle": "Buscar actualizaciones del firmware",
  "otaChecking": "Comprobando…",
  "currentVersion": "Versión actual",
  "latestVersion": "Última versión",
  "isLatestVersion": "La versión actual es la última existente.",
  "checkVersionFailed": "No se pudo verificar las actualizaciones de firmware",
  "retry": "Vuelva a intentarlo",
  "updateNow": "Actualizar",
  "updateTip": "Coloque el aspirador en el acoplador de recarga antes de actualizar y asegúrese de que el nivel de la batería sea superior al 15%.",
  "upgradeErr": "No se pudo actualizar",
  "updating": "Actualizando…",
  "updateTip2": "Al actualizar, no apague ni use el aspirador antes de que se complete la actualización.",
  "installing": "Instalando actualización…",
  "installtip": "El proceso de instalación requiere reiniciar el aspirador. Esto puede tomar un rato, sea paciente.",
  "updatesuccess": "Se ha actualizado correctamente",
  "upgradeErr1": "No se ha podido descargar el firmware",
  "upgradeErr5": "No se ha podido actualizar el firmware",
  "upgradeErr8": "El aspirador no se puede actualizar cuando no tenga carga",
  "upgradeErr7": "No se puede actualizar cuando el nivel de batería es demasiado bajo",
  "updateDialogTip": "Hay una actualización ({count}) de firmware ¿Actualizar ahora?",
  "forceTitle": "Hay una nueva versión del firmware.",
  "productGuide": "Ayuda",
  "deleteDevice": "Eliminar el dispositivo",
  "deveiceName": "Nombre del dispositivo",
  "deviceShare": "Uso compartido de dispositivos",
  "locationManager": "Gestión de localización",
  "otaCheck": "Actualización de firmware",
  "addDesktop": "Añadir acceso directo a la pantalla de inicio",
  "feedback": "Comentarios",
  "useTerms": "Información legal",
  "licenseTitle": "Acuerdo de usuario",
  "policyTitle": "Política de privacidad",
  "functionSetting": "Más ajustes",
  "generalSetting": "Ajustes generales",
  "securitySetting": "Ajustes de seguridad",
  "moreSetting": "Ajustes adicionales",
  "locationRobot": "Localizar mi aspirador",
  "areaEditTip1": "Es recomendable ajustar las áreas de acuerdo con el diseño real de la casa.",
  "areaMerge": "Unir",
  "areaSplit": "Dividir",
  "areaEditTip2": "Seleccione dos áreas adyacentes para fusionarlas",
  "selectOneSplit": "Seleccione un área para dividirla",
  "livingRoom": "Sala de Estar",
  "bedRoom": "Dormitorio",
  "kitchen": "Cocina",
  "washingRoom": "Baño",
  "balcony": "Balcón",
  "disturbTip": "No puede ser la misma que la hora de inicio, vuelva a configurar.",
  "customClean": "Zona",
  "autoClean": "Todo",
  "undefined": "Limpieza con fregona",
  "english": "Inglés",
  "addedAreaNum": "\nSe han añadido {count} habitaciones seleccionadas ",
  "local": "Parcial",
  "selectAreaClean": "Limpieza de habitación seleccionada",
  "selectArea": "Habitación",
  "selectAreaAfterSmartlearning": "Después de crear un mapa inteligente, puede usar la función de limpieza selectiva de habitaciones.",
  "timezoneTips": "¿Necesita sincronizar la zona horaria?",
  "otaSuccess": "Actualizar correctamente",
  "savedMapUse": "Úselo en el mapa guardado",
  "GuideKeepSweeperTips": "El aspiradora-fregona se recargará automáticamente toda vez que tenga un nivel bajo de carga mientras esté limpiando. Una vez se haya cargado hasta el nivel apropiado, el aspiradora-fregona seguirá limpiando el área restante.",
  "nokeepClean": "El aspiradora-fregona no reanudará la limpieza dentro del período de tiempo indicado",
  "keepSweeperOnpened": "Se ha activado el reanudado de limpieza a partir del punto de interrupción",
  "nodistrubTipOpened": "Se ha activado el modo de No molestar",
  "mop": "Trapeando",
  "offline": "Sin conexión",
  "upgrading": "Actualizando",
  "positioning": "Posicionando/Ubicando",
  "cleaningTime": "Tiempo de limpieza",
  "totalArea": "Área de limpieza",
  "maploading1": "Retirar el cabello enredado en la escobilla principal a tiempo",
  "maploading2": "El aspiradora-fregona se apagará de forma automática si se le deja en modo suspendido por más de 2 horas.",
  "maploading3": "Se puede limpiar el filtro con agua y volver a colocarlo una vez esté seco.",
  "maploading5": "El aspiradora-fregona se encenderá cuando se le coloque directamente sobre la base de carga.",
  "maploading6": "Retire todo cable y juguete del suelo antes de utilizar",
  "maploading7": "Limpie todos los sensores una vez el aspiradora-fregona haya sido utilizado por cierto período.",
  "maploading8": "No mueva el aspiradora-fregona a gran distancia durante la limpieza; puede que se pierda.",
  "dataLoadingErr": "No se han podido cargar los datos. Salga y vuelva a intentarlo.",
  "noMapChangeModeTips": "Úselo una vez se haya completado todo el mapa",
  "selectAreaNumMsg": "Limpiar {num} veces",
  "emptyMap": "No hay ningún mapa",
  "operateFaild": "La operación falló",
  "mergeTipMsg": "Una vez cierta área se haya combinado, el tiempo relativo a la misma ya no será válido",
  "areaToplimit": "Se ha alcanzado el máximo de divisiones",
  "splitTipMsg": "Una vez se haya dividido un área, el tiempo relativo a la misma ya no será válido",
  "areaNameWithSpeWords": "El nombre de un área no puede contener caracteres especiales",
  "studyRoom": "Estudio",
  "diningRoom": "Comedor",
  "corridor": "Corredor",
  "sundryRoom": "Lavadero",
  "cloakRoom": "Guardarropa",
  "mettingRoom": "Sala de estar",
  "office": "Oficina",
  "fitnessArea": "Gimnasio",
  "leisureArea": "Sala de juegos",
  "resetAreaMsg": "Se borrarán también los ajustes relativos al mapa. ¿Seguro de que desea continuar?",
  "resetSuccess": "Se ha restablecido lkos valores con éxito",
  "wifiMap": "Mapa Wi-Fi",
  "mapStrength": "Fuerte-Débil",
  "virtualLine": "Pared virtual",
  "cleanVirtualRect": "Zona a evitar",
  "mopVirtualRect": "Trapeado con Zona a evitar",
  "keepSweeperInfo": "El aspiradora-fregona seguirá realizando la limpieza restante una vez recargado.",
  "chargingWatertankTitle": "Retire el depósito de agua antes de cargar",
  "chargingWatertankInfo": "Retire el módulo de trapeado antes de recargar. Evite humedecer el suelo con ningún otro trapo humedo.",
  "resetMapTitle2": "Detalles del mensaje",
  "volume": "Voz y volumen",
  "keepSweeperTips": "Una vez encendido, el aspiradora-fregona se recargará automáticamente toda vez que tenga un nivel bajo de carga mientras esté limpiando. Tras cargarse hasta el nivel apropiado, el aspiradora-fregona seguirá limpiando el área restante.",
  "carpetCarpet": "Boost alfombra",
  "syncFail": "La sincronización fallo",
  "robotVolume": "Volumen del aspiradora-fregona",
  "volumeTip": "Deslice el control para ajustar el volumen de la voz ndel aspiradora-fregona mientras la escucha",
  "robotVoice": "Voz del aspiradora-fregona",
  "downloading": "Descargando",
  "downloadFail": "La descarga fallo",
  "invalidTiming": "El mapa ha cambiado; el tiempo ya no es válido.",
  "cleanScope": "Rango de limpieza",
  "drawOrder": "Pulse en los puntos principales del área para trazar una limpieza del aspiradora-fregona solicitada según los requisitos sucesivos de limpieza.",
  "noSelectAreaTip": "Seleccione un área a limpiar",
  "timingAutoRouteTip": "No ha añadido ningún pedido de limpieza, por lo que la misma será realizada en el orden predeterminado",
  "timingDrawRouteTip": "El aspiradora-fregona limpiará en el orden trazado",
  "timingInNoDisturb": "Las tareas programadas de limpieza se han programado para un período de No molestar. ¿Seguro que desea continuar?",
  "cleanInfoDetail": "Detalles de la limpieza",
  "cleanStatus": "Estado de la limpieza",
  "complete": "Completa",
  "break": "Interrumpir",
  "productUsageGuide": "Guía de uso del producto",
  "FAQ": "Preguntas frecuentes",
  "newEnvNewClean": "Se ha detectado una nueva ubicación; el aspiradora-fregona comenzará una nueva tarea de limpieza.",
  "moveBackToDock": "Regrese al aspiradora-fregona a la base de carga y el mapa se restaurará",
  "hotMap": "Mapa de calor",
  "carpetCarpetTips": "Una vez encendido, el aspiradora-fregona reconocerá la alfombra de forma automática, activará el nivel máximo de aspirado  y asimismo reanudará automáticamente el nivel normal de aspirado una vez salga de la alfombra.\n* Esto resulta muy efectivo cuando trabaja sobre un área en la que no hay alfombra.",
  "customAreaClean": "Limpieza zonificada",
  "loading": "Cargando datos...",
  "fullCleanup": "Limpieza completa",
  "msgSwitch": "Interruptor de notificaciones",
  "start": "Comenzar",
  "end": "Finalizar",
  "areaType": "Tipo de partición",
  "usageGuide": "Guía de uso",
  "cleanMopReminder": "Tras encender, el aspirador-fregona recordará limpiar el paño después del tiempo establecido ",
  "SNMismatch": "Este modelo no se admite en el área actual",
  "startNow": "Comenzar ahora",
  "cleanTimes": "Horas de limpieza",
  "mapManage": "Gestión de mapas",
  "guideDesc1": "Después de la limpieza deje que el aspirador con mopa regrese al muelle de carga automáticamente. El aspirador con mopa no puede aprender mapas si lo mueve manualmente al muelle de carga.",
  "guideDesc2": "En las características experimentales puede utilizar la función de guardar el mapa después de activar el Modo de ahorro de mapa.",
  "guideDesc3": "¿Cómo utilizo la limpieza por zonas y la función de la pared virtual?",
  "guideDesc4": "Habilite el Modo de ahorro de mapa en Ajustes > Características experimentales para aprender mapas con éxito, a fin de utilizar la limpieza de zonas y la función de muro virtual.",
  "productDetail": "Detalles de producto",
  "productInstructions": "Manual del producto",
  "nextStep": "Paso siguiente",
  "nodisturbTips": "Batería baja. El robot volverá al puerto para recargarse automáticamente. Una vez que la batería esté cargada por completo, el robot continuará con la limpieza. Para garantizar un entorno de sueño tranquilo, se recomienda ajustar a un período de tiempo no molesto.",
  "startExper": "Comenzar a experimentar",
  "timingStart": "Abrir",
  "noviceStudyTip1": "El modo silencioso es ideal para limpiar en un entorno silencioso, con menor ruido de succión y mayor duración de la batería.",
  "noviceStudyTip2": "El modo estándar es ideal para limpiar en entornos normales, con menos ruido de succión y larga duración de la batería",
  "raterRegulate": "Ajuste del flujo de agua",
  "studyMopTip1": "El flujo de agua bajo es ideal para la limpieza de suelos húmedos",
  "studyMopTip2": "El flujo de agua medio es ideal para la limpieza general",
  "studyMopTip3": "El flujo de agua alto es ideal para la limpieza de suelos sucios",
  "majorFunction": "Funciones principales",
  "studyClean": "Limpieza",
  "studyCharge": "Recarga",
  "cleanAvoidTips": "Cuando el robot está funcionando, evita automáticamente la Zona de Pared Virtual",
  "restrictedAreaTips": "El robot no entrará en esta zona en el modo de aspiración y fregado",
  "restrictedAreaMopTips": "El área restringida de fregado es solo para prohibir que el robot acceda al área en el modo de fregado",
  "restrictedAreaClean": "Limpieza del área restringida",
  "LineCountTips": "El número de Paredes Virtuales ha alcanzado el límite.",
  "cleanRectCountTips": "El número de áreas restringidas de limpieza ha alcanzado el límite",
  "mopRectCountTips": "El número de áreas restringidas para fregar ha alcanzado el límite",
  "save": "Guardar",
  "noSave": "No guardar",
  "splitErr1": "La zona de división es inferior a 1 metro cuadrado; fallo de división",
  "splitErr2": "El final de la línea de división no está en el límite de la zona de división; fallo de división",
  "messageList": "Lista de avisos de mensajes",
  "messageTips": "Avisos de mensaje, consultar",
  "faultList": "Lista de mensajes de error",
  "faultMessageList": "Lista de errores y mensajes",
  "faultTips": "Avisos de error, gestionar",
  "clothCleanDialog": "Limpieza con fregona (solo fregona)",
  "cleanMin": "{num}minutos después",
  "mapChaged": "El mapa cambió",
  "noComplete": "No finalizado",
  "selectAreaCountMsg": "Áreas seleccionadas: {count}"
};