module.exports = {
  "guideTipTitle1": "Organisez votre intérieur",
  "guideTipDesc1": "Disposez les meubles, comme les tables et les chaises, de façon ordonnée pour créer de l’espace pour le nettoyage. Rangez les objets qui traînent au sol pour éviter de bloquer l’appareil",
  "guideTipTitle2": "Disposez le socle de recharge correctement",
  "guideTipDesc2": "Ne laissez pas d’obstacles près du socle de recharge. Attachez le câble d’alimentation du socle pour éviter que l’aspirateur-balai ne se prenne dedans.",
  "guideTipTitle3": "Assurez-vous que l'éclairage intérieur est suffisant.",
  "guideTipDesc3": "Gardez l’espace devant être nettoyé éclairé, afin que l’aspirateur-balai fonctionne de manière optimale.",
  "cleaning": "Nettoyage",
  "pause": "Suspendre",
  "waiting": "En veille",
  "charging": "En charge",
  "gocharging": "Frais de retour",
  "completedCharge": "Chargement terminé",
  "localClean": "Nettoyage partiel",
  "strongModeTip": "Le réglage fort convient au nettoyage des tapis. Quand l’aspiration est augmentée, le bruit s’intensifie légèrement et l’autonomie de la batterie diminue.",
  "turboModeTip": "Le réglage turbo convient au nettoyage des tapis à poils longs. Quand l’aspiration est augmentée, le bruit s’intensifie légèrement et l’autonomie de la batterie diminue.",
  "experimental": "Fonctionnalités expérimentales",
  "mapsavemode": "Mode d’enregistrement des cartes",
  "mapsavetip": "Lorsque ce mode est activé, les cartes intelligentes sont continuellement optimisées. Vous pouvez les enregistrer, définir des murs virtuels et des zones restreintes, etc.",
  "SmartLearning": "Création d’une carte intelligente…",
  "SmartLearningTip": "Une fois que l’appareil a effectué plusieurs nettoyages dans différentes conditions d’éclairage, la carte est enregistrée et peut être utilisée pour différentes fonctions (nettoyage de zone, mur virtuel, etc.).",
  "SmartLearningTip2": "Lorsque vous démarrez un nettoyage, ouvrez toutes les portes de votre domicile, afin de garantir la création d’une carte correcte.",
  "saveMapTip1": "Désactivez le robot aspirateur laveur si aucune tâche de nettoyage n’est prévue.",
  "saveMapTip2": "Une fois qu’il est désactivé, la carte enregistrée et les paramètres associés sont effacés.",
  "zonedStopTaskMsg": "Cette opération interrompra la tâche en cours. Voulez-vous vraiment continuer ?",
  "cleanTip": "Terminer le nettoyage actuel, et retourner à la station pour charger?",
  "customAreaAfterSmartlearning": "Une fois la carte intelligente créée, vous pouvez utiliser la fonctionnalité de nettoyage de zone.",
  "customAreaMsg": "Le robot aspirateur laveur nettoiera l’espace au sein de la zone indiquée.",
  "areaManage": "Éditeur de zone",
  "reset": "Réinitialiser",
  "renameNoSelect": "Veuillez sélectionner une zone pour renommer",
  "resetFail": "Échec de la réinitialisation",
  "restricted_area": "Mur virtuel/zone restreinte",
  "virtualWallPageTips": "Ne vous fiez pas aux zones restreintes et aux murs virtuels définis pour assurer l’isolement des zones dangereuses.",
  "virtualAreaMsg": "Voulez-vous enregistrer les paramètres des zones restreintes et murs virtuels définis ?",
  "virtualRactCountMsg": "Le nombre maximal de murs virtuels ou de zones restreintes est atteint.",
  "chargerCoveredRect": "Les zones restreintes ne peuvent pas recouvrir l’espace dans lequel se trouve le socle de charge.",
  "chargerCoveredLine": "Les murs virtuels ne peuvent pas traverser la zone du socle de charge.",
  "keepSweeperTitle": "Reprendre le nettoyage",
  "resetMapTitle": "L’itinéraire de nettoyage ne correspond pas à l’itinéraire défini.",
  "resetMapTip2": "Nous vous recommandons de réinitialiser la carte et de balayer toutes les zones dans des conditions d'éclairage adéquates.",
  "reset_map": "Réinitialiser la carte",
  "heapWarnTitle1": "Le filtre est presque épuisé",
  "heapWarnMsg1": "Le filtre est presque épuisé, veuillez le remplacer aussitôt que possible.",
  "heap": "Filtre",
  "remain": "Restant",
  "remainDay": "Durée de vie restante : Environ {hour} heures",
  "heapDesc": "Le filtre est fait de fibres de polymère qui empêche à la poussière de s'échapper du compartiment. Au fil du temps, il se bouchera petit à petit et perdra de son efficacité. Par conséquent, il est recommandé de remplacer le filtre toutes les {time} heures de fonctionnement ou moins.",
  "materialReset": "Réinitialisation de {name}",
  "buy": "Acheter maintenant",
  "resetHeapMessage": "Le filtre a-t-il été remplacé avec un nouveau filtre?",
  "slidBrushWarnTipTitle1": "La brosse latérale nécessite un remplacement imminent",
  "slidBrushWarnTipMsg1": "La brosse latérale est presque usée. Veuillez la remplacer aussitôt que possible.",
  "slidBrush": "Brosse latérale",
  "slidBrushDesc": "La brosse principale dirige les saletés et les débris des coins vers la brosse principale. Au fil du temps, elle va s'user et perdre de son efficacité. Par conséquent, il est recommandé de remplacer la brosse latérale après toutes les {time} heures de fonctionnement ou moins.",
  "resetSlidBrushMessage": "La brosse latérale a-t-elle été remplacée avec une nouvelle?",
  "rollingBrushWarnTitle1": "La brosse principale doit être remplacée bientôt",
  "rollingBrushWarnMsg1": "La brosse principale est presque usée. Veuillez la remplacer aussitôt que possible.",
  "rollingBrush": "Brosse principale",
  "rollingBrushDesc": "La brosse principale dirige les saletés et les débris dans le compartiment à poussière de l'aspirateur laveur. Au fil du temps, elle va s'user et perdre de son efficacité. Par conséquent, il est recommandé de remplacer la brosse principale toutes les {time} heures de fonctionnement ou moins.",
  "resetRollingBrushMessage": "La brosse principale a-t-elle été remplacée avec une nouvelle?",
  "heapWarnTitle2": "Le filtre est épuisé",
  "heapWarnMsg2": "Le filtre est épuisé, veuillez le remplacer.",
  "slidBrushWarnTipTitle2": "La brosse latérale doit être remplacée",
  "slidBrushWarnTipMsg2": "La brosse latérale est use, veuillez la remplacer.",
  "rollingBrushWarnTitle2": "La brosse principale doit être remplacée",
  "rollingBrushWarnMsg2": "La brosse principale est usée, veuillez la replacer.",
  "warnInfoTitle": "Détails d'erreur",
  "morequestion": "Plus d'informations sur les commentaires",
  "feedback2": "Commentaires",
  "setting": "Paramètres",
  "robotSetting": "Réglages de l'appareil",
  "timeZone": "Fuseau horaire de l'aspirateur laveur",
  "disturbTime": "Mode DND",
  "nodistrubTip": "Lorsque l'aspirateur laveur est actif, il ne reprendra pas automatiquement les nettoyages lors de la période spécifiée. Toutefois, les nettoyages programmés seront toujours effectués lors de la période DND.",
  "timezoneTip1": "Vous pouvez synchroniser le fuseau horaire de votre téléphone avec l'aspirateur laveur pour vous assurer que les deux sont dans le même fuseau horaire.",
  "timezoneTip2": "* Lorsque le fuseau horaire de l'aspirateur laveur est imprécis, les nettoyages programmés et le mode DND peuvent ne pas fonctionner comme souhaité.",
  "syncTimeZone": "Synchroniser maintenant",
  "syncSuccess": "Synchronisation réussie",
  "famaleVoice": "Voix féminine",
  "used": "Courant",
  "use": "Utiliser",
  "cleanTiming": "Réglage de l'heure",
  "noTiming": "Aucun programme",
  "once": "Une fois",
  "Monday": "Lun.",
  "Tuesday": "Mar.",
  "Wednesday": "Mer.",
  "Thursday": "Jeu.",
  "Friday": "Ven.",
  "Saturday": "Sam.",
  "Sunday": "Dim.",
  "workDay": "Jours ouvrables (Lun. – Ven.)",
  "weekend": "Le week-end",
  "everyDay": "Chaque jour",
  "modeQuiet": "Silencieux",
  "modeStandard": "Standard",
  "modeMedium": "Fort",
  "modeStrong": "Turbo",
  "low": "Bas",
  "middle": "Moyen",
  "high": "Élevé",
  "startTime": "Heure de début",
  "repeat": "Répéter",
  "cleanMode": "Mode de nettoyage",
  "waterVolume": "Réglage du niveau d'eau",
  "sure": "OK",
  "cancle": "Annuler",
  "deleteMsg": "Supprimer ce programme",
  "networkTimeout": "Demande expirée",
  "timingNumTip": "Le nettoyage programmé maximal a été atteint, impossible d'ajouter un nettoyage programmé.",
  "cleanLog": "Historique de nettoyage",
  "totalTime": "Temps total",
  "totalAreas": "Zone totale",
  "totalTimes": "Nombre total",
  "emptyLog": "L'historique est vide",
  "materialTime": "Programme d'entretien",
  "brushExpireDesc": "Remplacez dans environ {time} heures",
  "Instructions": "Instructions",
  "otatitle": "Vérifier les mises à jour du micrologiciel",
  "otaChecking": "Vérification en cours…",
  "currentVersion": "Version actuelle",
  "latestVersion": "Dernière version",
  "isLatestVersion": "La version en cours est la plus récente",
  "checkVersionFailed": "Impossible de vérifier les mises à jour du micrologiciel",
  "retry": "Réessayez",
  "updateNow": "Mise à jour",
  "updateTip": "Placez l'aspirateur laveur sur la station de charge avant de mettre à jour et rassurez-vous que le niveau de batterie est supérieur à 15 %.",
  "upgradeErr": "Mise à jour impossible",
  "updating": "Mise à jour en cours…",
  "updateTip2": "Mise à jour en cours, n'éteignez pas ou n'utilisez pas l'aspirateur laveur avant que la mise à jour ne se soit terminée.",
  "installing": "Installation des mises à jour en cours...",
  "installtip": "Le processus d'installation exige de redémarrer l'aspirateur laveur. Ceci peut prendre un moment, veuillez patienter.",
  "updatesuccess": "Mise à jour réussie",
  "upgradeErr1": "Impossible de télécharger le micrologiciel",
  "upgradeErr5": "Mise à jour du micrologiciel impossible",
  "upgradeErr8": "L'aspirateur laveur ne peut être mis à jour pendant la charge",
  "upgradeErr7": "Impossible de mettre à jour lorsque le niveau de batterie est faible",
  "updateDialogTip": "Mise à jour du firmware ({count}) disponible. Mettre à jour maintenant ?",
  "forceTitle": "Nouvelle version du micrologiciel disponible",
  "productGuide": "Aide",
  "deleteDevice": "Supprimer l'appareil",
  "deveiceName": "Nom de l'apppareil",
  "deviceShare": "Partage sur dispositif",
  "locationManager": "Gestion de la localisation",
  "otaCheck": "Mise à jour du micrologiciel",
  "addDesktop": "Ajouter un raccourci vers l'écran d'accueil",
  "feedback": "Commentaires",
  "useTerms": "Informations légales",
  "licenseTitle": "Contrat d'utilisation",
  "policyTitle": "Politique de confidentialité",
  "functionSetting": "Plus de paramètres",
  "generalSetting": "Paramètres généraux",
  "securitySetting": "Paramètres de sécurité",
  "moreSetting": "Réglages supplémentaires",
  "locationRobot": "Localiser mon aspirateur laveur",
  "areaEditTip1": "Il est recommandé de régler les zones en fonction la disposition actuelle de la maison.",
  "areaMerge": "Fusionner",
  "areaSplit": "Diviser",
  "areaEditTip2": "Veuillez sélectionner deux zones adjacentes pour fusionner",
  "selectOneSplit": "Veuillez sélectionner une zone pour diviser",
  "livingRoom": "Séjour ",
  "bedRoom": "Chambre",
  "kitchen": "Cuisine",
  "washingRoom": "Salle de bain",
  "balcony": "Balcon",
  "disturbTip": "Impossible d'être le même que le temps de démarrage, veuillez initialiser à nouveau.",
  "customClean": "Zone",
  "autoClean": "Tout",
  "undefined": "Nettoyage à serpillière",
  "english": "Anglais",
  "addedAreaNum": "\n{count} chambres sélectionnées ont été ajoutées.",
  "local": "Partiel ",
  "selectAreaClean": "Nettoyage de la chambre sélectionnée",
  "selectArea": "Chambre",
  "selectAreaAfterSmartlearning": "Après avoir créé une carte intelligente, vous pouvez utiliser la fonction de nettoyage des chambres sélectionnées.",
  "timezoneTips": "Avez-vous besoin de synchroniser le fuseau horaire.",
  "otaSuccess": "Mise à jour réussie",
  "savedMapUse": "Veuillez l'utiliser sur la carte sauvegardée",
  "GuideKeepSweeperTips": "Le balai aspirateur sera automatiquement rechargé lorsque la puissance est faible pendant le nettoyage. Le balai aspirateur continuera à nettoyer la zone non nettoyée après avoir été rechargé à la puissance appropriée.",
  "nokeepClean": "Le balai aspirateur ne reprendra pas le nettoyage dans un délai déterminé ",
  "keepSweeperOnpened": "Le nettoyage des points de rupture a été activé",
  "nodistrubTipOpened": "Le mode \"Ne pas déranger\" a été activé",
  "mop": "Essuyage",
  "offline": "Hors ligne",
  "upgrading": "Mise à jour",
  "positioning": "Positionnement / Localisation",
  "cleaningTime": "Temps de nettoyage",
  "totalArea": "Zone de nettoyage",
  "maploading1": "Enlever à temps les poils emmêlés sur la brosse principale",
  "maploading2": "Le balai aspirateur s'arrêtera automatiquement s'il est laissé en mode veille pendant plus de 2 heures.",
  "maploading3": "Le filtre peut être nettoyé à l'eau et réinstallé après avoir été séché.",
  "maploading5": "Le balai aspirateur se mettra en marche lorsqu'il est placé directement sur le socle de chargement.",
  "maploading6": "Retirez les cordons et les jouets se trouvant au sol avant l'utilisation",
  "maploading7": "Veuillez essuyer tous les capteurs après que le balai aspirateur ait fonctionné un certain temps",
  "maploading8": "Ne déplacez pas le balai aspirateur sur une grande distance pendant le nettoyage, il pourrait se perdre",
  "dataLoadingErr": "Le chargement des données a échoué, veuillez sortir et réessayer",
  "noMapChangeModeTips": "Veuillez l'utiliser une fois la carte complétée",
  "selectAreaNumMsg": "Nettoyage {num} fois",
  "emptyMap": "Pas de carte",
  "operateFaild": "L'opération a échoué",
  "mergeTipMsg": "Après la fusion d'une zone, le calendrier lié à cette zone ne sera pas valable",
  "areaToplimit": "La partition a atteint le maximum",
  "splitTipMsg": "Après le découpage d'une zone, le délai lié à cette zone sera invalide",
  "areaNameWithSpeWords": "Le nom de la zone ne peut pas contenir de caractères spéciaux",
  "studyRoom": "Étude",
  "diningRoom": "Salle à manger",
  "corridor": "Couloir",
  "sundryRoom": "Buanderie",
  "cloakRoom": "Vestiaire",
  "mettingRoom": "Salon",
  "office": "Bureau",
  "fitnessArea": "Espace fitness",
  "leisureArea": "Espace de loisirs",
  "resetAreaMsg": "Les paramètres se rapportant à la carte seront également supprimés. Continuer ou non ?",
  "resetSuccess": "Réinitialisé avec succès",
  "wifiMap": "Carte Wi-Fi",
  "mapStrength": "Fort - Faible",
  "virtualLine": "Mur virtuel",
  "cleanVirtualRect": "Zone interdite",
  "mopVirtualRect": "Nettoyage de la zone interdite",
  "keepSweeperInfo": "Le balai aspirateur continuera à effectuer les tâches de nettoyage non terminées après avoir été rechargé",
  "chargingWatertankTitle": "Enlever le réservoir d'eau avant de charger",
  "chargingWatertankInfo": "Retirez le module de nettoyage avant de le recharger. Évitez de mouiller les balais à franges pour humidifier le sol.",
  "resetMapTitle2": "Détails du message",
  "volume": "Voix et volume",
  "keepSweeperTips": "Après avoir été mis en marche, le balai aspirateur se recharge automatiquement lorsque la puissance est faible pendant le nettoyage. Le balai aspirateur continuera à nettoyer la zone non nettoyée après avoir été rechargé à la puissance appropriée.",
  "carpetCarpet": "Boost tapis",
  "syncFail": "Sync échouée",
  "robotVolume": "Volume du balai aspirateur",
  "volumeTip": "Faites glisser le curseur pour régler et écouter le volume de la voix du balai aspirateur",
  "robotVoice": "Voix de balai aspirateur",
  "downloading": "Téléchargement",
  "downloadFail": "Echec du téléchargement",
  "invalidTiming": "La carte a changé, et le timing n'est pas valable",
  "cleanScope": "Gamme de nettoyage",
  "drawOrder": "Appuyez sur les points chauds de la zone pour dessiner un ordre de nettoyage du balai aspirateur en fonction des besoins de nettoyage successifs.",
  "noSelectAreaTip": "Veuillez sélectionner une zone de nettoyage",
  "timingAutoRouteTip": "Vous n'avez pas ajouté d'ordre de nettoyage, cela sera exécuté dans l'ordre par défaut",
  "timingDrawRouteTip": "Le balai aspirateur nettoiera dans l'ordre de la trajectoire tracée",
  "timingInNoDisturb": "Les tâches de nettoyage programmées sont mises en place pendant la période de non perturbation. Poursuivre ou non ?",
  "cleanInfoDetail": "Détails du nettoyage",
  "cleanStatus": "État d'avancement du nettoyage",
  "complete": "Compléter",
  "break": "Interrompre",
  "productUsageGuide": "Guide d'utilisation des produits",
  "FAQ": "FAQ",
  "newEnvNewClean": "Un nouvel emplacement détecté, le balai aspirateur va commencer une nouvelle tâche de nettoyage.",
  "moveBackToDock": "Déplacez le balai aspirateur vers le socle de chargement et la carte sera alors restaurée",
  "hotMap": "Carte de chaleur",
  "carpetCarpetTips": "Après avoir été mis en marche, le balai aspirateur reconnaîtra automatiquement le tapis, activera la succion maximale et reprendra automatiquement la succion normale après avoir quitté le tapis.                              *Il est efficace dès qu'il commence à travailler dans une zone sans tapis.",
  "customAreaClean": "Nettoyage zoné",
  "loading": "Chargement des données...",
  "fullCleanup": "Nettoyage complet",
  "msgSwitch": "Commutateur de notifications",
  "start": "Démarrage",
  "end": "Fin",
  "areaType": "Type de partition",
  "usageGuide": "Guide d'utilisation",
  "cleanMopReminder": "Après la mise en marche, l'aspirateur à balai rappellera de nettoyer le torchon après le temps fixé",
  "SNMismatch": "Ce modèle n'est pas pris en charge dans le domaine actuel",
  "startNow": "Commencer maintenant",
  "cleanTimes": "Heures de nettoyage",
  "mapManage": "Gestion des cartes",
  "guideDesc1": "À la fin du nettoyage, veuillez laisser le robot aspirateur laveur revenir automatiquement à la station de charge. Le robot aspirateur laveur ne peut pas apprendre de cartes si vous le replacez vous-même sur sa station de charge.",
  "guideDesc2": "À titre expérimental, vous pouvez utiliser la fonction d’enregistrement des cartes une fois le Mode d’enregistrement des cartes activé.",
  "guideDesc3": "Comment puis-je utiliser les fonctionnalités de nettoyage zoné et de mur virtuel ?",
  "guideDesc4": "Activez le Mode d’enregistrement des cartes dans la zone Réglages > Fonctionnalités expérimentales pour permettre au robot d’apprendre des cartes, et pour utiliser le nettoyage zoné et les murs virtuels.",
  "productDetail": "Détails du produit",
  "productInstructions": "Manuel du produit",
  "nextStep": "Prochaine étape",
  "nodisturbTips": "Pile faible. Le robot retournera à la station d'accueil pour se recharger automatiquement. Une fois la batterie complètement chargée, le robot continuera le nettoyage. Afin de garantir un environnement de sommeil calme, il est recommandé de programmer une période de non dérangement.",
  "startExper": "Commencer à expérimenter",
  "timingStart": "Ouvrir",
  "noviceStudyTip1": "Le mode silencieux est adapté au nettoyage en milieu silencieux, avec le moins de bruit d'aspiration et une durée de vie de la pile la plus longue",
  "noviceStudyTip2": "Le mode standard est adapté au nettoyage dans un environnement ordinaire, avec moins de bruit d'aspiration et une longue durée de vie de la pile",
  "raterRegulate": "Ajustement du débit d'eau",
  "studyMopTip1": "Un débit d'eau faible convient au nettoyage des sols mouillés",
  "studyMopTip2": "Un débit d'eau moyen convient pour le nettoyage général",
  "studyMopTip3": "Le débit d'eau élevé convient au nettoyage des sols sales",
  "majorFunction": "Fonctions principales",
  "studyClean": "Nettoyage",
  "studyCharge": "Recharge",
  "cleanAvoidTips": "Lorsque le robot fonctionne, il évite automatiquement la zone de mur virtuel",
  "restrictedAreaTips": "Le robot n'entrera pas dans cette zone en mode aspiration et balayage",
  "restrictedAreaMopTips": "La zone restreinte de balayage est uniquement destinée à interdire au robot d'entrer dans cette zone en mode balayage",
  "restrictedAreaClean": "Nettoyage de la zone réglementée",
  "LineCountTips": "Le nombre de murs virtuels a atteint la limite",
  "cleanRectCountTips": "Le nombre de zones de nettoyage à accès restreint est arrivé à la limite",
  "mopRectCountTips": "Le nombre de zones d'interdiction du nettoyage a atteint la limite",
  "save": "Sauvegarder",
  "noSave": "Ne pas sauvegarder",
  "splitErr1": "La zone de répartition est inférieure à 1 mètre carré ; la répartition échoue",
  "splitErr2": "L'extrémité de la ligne de division ne se trouve pas à la limite de la zone de répartition ; la répartition échoue",
  "messageList": "Liste de messages d'alerte",
  "messageTips": "Des messages s'affichent, veuillez les consulter",
  "faultList": "Liste de messages d'erreur",
  "faultMessageList": "Liste des défauts et des messages",
  "faultTips": "Messages d'erreur, veuillez la prendre en charge",
  "clothCleanDialog": "Nettoyage à serpillière (uniquement nettoyage)",
  "cleanMin": "{num} minutes plus tard",
  "mapChaged": "Carte modifiée",
  "noComplete": "Inachevé ",
  "selectAreaCountMsg": "Zones sélectionnées : {count}"
};