module.exports = {
  "guideTipTitle1": "Una casa organizzata",
  "guideTipDesc1": "Disporre i mobili, ad esempio tavoli e sedie, in modo ordinato per creare spazio per la pulizia. Organizzare gli oggetti sparsi sul pavimento per evitare che il dispositivo sia ostacolato o rimanga bloccato.",
  "guideTipTitle2": "Disporre correttamente la stazione di ricarica.",
  "guideTipDesc2": "Non lasciare ostacoli intorno alla stazione di ricarica. Legare il cavo di alimentazione della stazione di ricarica in modo da evitare che l'aspirapolvere/lavapavimenti rimanga impigliato nel cavo.",
  "guideTipTitle3": "Assicurarsi che l'ambiente sia ben illuminato.",
  "guideTipDesc3": "Mantenere illuminata l'area da pulire, in modo che l'aspirapolvere/lavapavimenti possa pulire in modo ottimale.",
  "cleaning": "Pulizia",
  "pause": "Pausa",
  "waiting": "Standby",
  "charging": "Ricarica",
  "gocharging": "Addebito di ritorno",
  "completedCharge": "Ricarica completata",
  "localClean": "Pulizia parziale",
  "strongModeTip": "L'impostazione ad alta potenza è adatta per la pulizia dei tappeti. Se si aumenta l'aspirazione, aumenterà leggermente il livello di rumore e diminuirà la durata della batteria.",
  "turboModeTip": "L'impostazione turbo è adatta per la pulizia dei tappeti a pelo lungo. Se si aumenta l'aspirazione, aumenterà leggermente il livello di rumore e diminuirà la durata della batteria.",
  "experimental": "Funzioni sperimentali",
  "mapsavemode": "Modalità di memorizzazione mappe",
  "mapsavetip": "Una volta attivate, le mappe intelligenti vengono costantemente migliorate; inoltre, è possibile memorizzare mappe, impostare pareti virtuali e aree limitate, etc.",
  "SmartLearning": "Creazione di mappa intelligente in corso...",
  "SmartLearningTip": "Dopo aver effettuato diverse pulizie in condizioni di illuminazione variabili, la mappa viene memorizzata e può essere utilizzata per funzioni quali pulizia a zone e pareti virtuali.",
  "SmartLearningTip2": "Per garantire la completezza della mappa, aprire tutte le porte di casa quando si inizia una pulizia.",
  "saveMapTip1": "Spegnere l’aspirapolvere/lavapavimenti quando non ci sono attività di pulizia.",
  "saveMapTip2": "Una volta disattivata, la mappa salvata e la relativa impostazione verranno cancellate.",
  "zonedStopTaskMsg": "Questa azione interromperà l’attività corrente. Continuare?",
  "cleanTip": "Terminare la pulizia corrente e tornare alla base per caricare?",
  "customAreaAfterSmartlearning": "Dopo aver creato una mappa intelligente, è possibile utilizzare la funzione di pulizia a zone.",
  "customAreaMsg": "L'aspirapolvere/lavapavimenti pulirà all'interno della zona circoscritta",
  "areaManage": "Editor di area",
  "reset": "Ripristino",
  "renameNoSelect": "Seleziona un'area da rinominare",
  "resetFail": "Ripristino non riuscito",
  "restricted_area": "Parete virtuale/area limitata",
  "virtualWallPageTips": "Evitare di ricorrere ad aree limitate e pareti virtuali per isolare le aree pericolose.",
  "virtualAreaMsg": "Salvare le impostazioni correnti relative ad aree limitate e pareti virtuali?",
  "virtualRactCountMsg": "È stato raggiunto il numero massimo di pareti virtuali o aree soggette a restrizioni.",
  "chargerCoveredRect": "Le aree limitate non possono includere quella in cui è posizionata la stazione di ricarica.",
  "chargerCoveredLine": "Le pareti virtuali non possono sovrapporsi alla stazione di ricarica.",
  "keepSweeperTitle": "Riprendi pulizia",
  "resetMapTitle": "Percorso pulizia non corrispondente.",
  "resetMapTip2": "Ripristinare la mappa e illuminare bene le aree da pulire.",
  "reset_map": "Ripristina mappa",
  "heapWarnTitle1": "Il filtro è quasi esaurito",
  "heapWarnMsg1": "Il filtro è quasi esaurito, sostituirlo il prima possibile.",
  "heap": "Filtro",
  "remain": "Rimanente",
  "remainDay": "Durata residua: ca. {hour} ore",
  "heapDesc": "Il filtro è realizzato in fibre polimeriche per impedire alla polvere di fuoriuscire dal vano della polvere. Nel tempo, si bloccherà lentamente e perderà la sua efficacia. Pertanto, si consiglia di sostituire il filtro ogni {time} ore di funzionamento o meno.",
  "materialReset": "Reimposta {name}",
  "buy": "Acquista adesso",
  "resetHeapMessage": "Il filtro è stato sostituito con uno nuovo?",
  "slidBrushWarnTipTitle1": "La spazzola laterale deve essere sostituita presto",
  "slidBrushWarnTipMsg1": "La spazzola laterale è quasi usurata, sostituirla il prima possibile.",
  "slidBrush": "Spazzola laterale",
  "slidBrushDesc": "La spazzola laterale dirige sporco e detriti dagli angoli verso la spazzola principale. Nel tempo, si usurerà e perderà la sua efficacia. Pertanto, si consiglia di sostituire la spazzola laterale ogni {time} ore di funzionamento o meno.",
  "resetSlidBrushMessage": "La spazzola laterale è stata sostituita con una nuova?",
  "rollingBrushWarnTitle1": "La spazzola principale deve essere sostituita presto",
  "rollingBrushWarnMsg1": "La spazzola principale è quasi usurata, sostituirla il prima possibile.",
  "rollingBrush": "Spazzola Principale",
  "rollingBrushDesc": "La spazzola principale dirige sporco e detriti nel vano polvere dell'aspirapolvere/pulisci pavimenti. Nel tempo, si usurerà e perderà la sua efficacia. Pertanto, si consiglia di sostituire la spazzola principale ogni {time} ore di funzionamento o meno.",
  "resetRollingBrushMessage": "La spazzola principale è stata sostituita con una nuova?",
  "heapWarnTitle2": "Il filtro è esaurito",
  "heapWarnMsg2": "Il filtro è esaurito, sostituirlo.",
  "slidBrushWarnTipTitle2": "La spazzola laterale deve essere sostituita",
  "slidBrushWarnTipMsg2": "La spazzola laterale è usurata, sostituirla.",
  "rollingBrushWarnTitle2": "La spazzola principale deve essere sostituita",
  "rollingBrushWarnMsg2": "La spazzola principale èusurata, sostituirla.",
  "warnInfoTitle": "Dettagli errore",
  "morequestion": "Ulteriori dettagli sul feedback",
  "feedback2": "Feedback",
  "setting": "Impostazioni",
  "robotSetting": "Impostazioni dispositivo",
  "timeZone": "Zona temporale del mio aspirapolvere/pulisci pavimenti",
  "disturbTime": "Modalità DND",
  "nodistrubTip": "Se abilitato, l'aspirapolvere/pulisci pavimenti non riprenderà automaticamente le pulizie durante il periodo specificato. Tuttavia, le pulizie programmate verranno comunque eseguite durante il periodo di DND.",
  "timezoneTip1": "Puoi sincronizzare la zona temporale del tuo telefono con il tuo aspirapolvere/pulisci pavimenti, per assicurarti che entrambi si trovino nella stessa zona temporale.",
  "timezoneTip2": "* Quando la zona temporale dell'aspirapolvere/pulisci pavimenti non è precisa, le pulizie programmate e la modalità DND potrebbero non funzionare come previsto.",
  "syncTimeZone": "Sincronizza ora",
  "syncSuccess": "Sincronizzazione avvenuta con successo",
  "famaleVoice": "Voce femminile",
  "used": "Corrente",
  "use": "Utilizza",
  "cleanTiming": "Programmare l’impostazione",
  "noTiming": "Nessun programma",
  "once": "Una volta",
  "Monday": "Lun",
  "Tuesday": "Mar",
  "Wednesday": "Mer",
  "Thursday": "Gio",
  "Friday": "Ven",
  "Saturday": "Sab",
  "Sunday": "Dom",
  "workDay": "Giorni lavorativi (lun - ven)",
  "weekend": "Fine settimana",
  "everyDay": "Quotidiano",
  "modeQuiet": "Silenzioso",
  "modeStandard": "Standard",
  "modeMedium": "Alta potenza",
  "modeStrong": "Turbo",
  "low": "Basso",
  "middle": "Medio",
  "high": "Elevata",
  "startTime": "Ora di inizio",
  "repeat": "Ripeti",
  "cleanMode": "Modalità di pulizia",
  "waterVolume": "Impostazione del livello dell'acqua",
  "sure": "OK",
  "cancle": "Annulla",
  "deleteMsg": "Eliminare la pianificazione",
  "networkTimeout": "Timeout richiesta",
  "timingNumTip": "La max. pulizia programmata è stata raggiunta, impossibile aggiungere una pulizia programmata.",
  "cleanLog": "Cronologia della pulizia",
  "totalTime": "Tempo totale",
  "totalAreas": "Area totale",
  "totalTimes": "Tempi totali",
  "emptyLog": "La cronologia è vuota",
  "materialTime": "Programma di servizio",
  "brushExpireDesc": "Sostituisci tra circa {time} ore",
  "Instructions": "Istruzioni",
  "otatitle": "Controlla se sono disponibili aggiornamenti del firmware",
  "otaChecking": "Controllo in corso…",
  "currentVersion": "Versione in uso",
  "latestVersion": "Versione più recente",
  "isLatestVersion": "La versione in uso è la più recente.",
  "checkVersionFailed": "Impossibile controllare gli aggiornamenti firmware",
  "retry": "Riprova",
  "updateNow": "Aggiorna",
  "updateTip": "Posizionare l'aspirapolvere/pulisci pavimenti sulla base di ricarica prima dell'aggiornamento e assicurati che il livello della batteria sia superiore al 15%.",
  "upgradeErr": "Aggiornamento non riuscito",
  "updating": "Aggiornamento in corso...",
  "updateTip2": "In aggiornamento, non spegnere o utilizzare l'aspirapolvere/pulisci pavimenti prima che l'aggiornamento sia completato.",
  "installing": "Installazione aggiornamenti in corso...",
  "installtip": "Il processo di installazione richiede il riavvio dell'aspirapolvere/pulisci pavimenti. Questo potrebbe richiedere del tempo, sii paziente.",
  "updatesuccess": "Aggiornamento completato",
  "upgradeErr1": "Impossibile scaricare il firmware",
  "upgradeErr5": "Impossibile aggiornare il firmware",
  "upgradeErr8": "L'aspirapolvere/pulisci pavimenti non può essere aggiornato mentre non è in carica",
  "upgradeErr7": "Impossibile aggiornare mentre il livello della batteria è troppo basso",
  "updateDialogTip": "Disponibile aggiornamento firmware ({count}). Aggiornare adesso?",
  "forceTitle": "Nuova versione del firmware disponibile",
  "productGuide": "Guida",
  "deleteDevice": "Elimina dispositivo",
  "deveiceName": "Nome dispositivo",
  "deviceShare": "Condivisione dispositivo",
  "locationManager": "Gestione delle sedi",
  "otaCheck": "Aggiornamento firmware",
  "addDesktop": "Aggiungi collegamento schermata iniziale",
  "feedback": "Feedback",
  "useTerms": "Informazioni legali",
  "licenseTitle": "Contratto di licenza",
  "policyTitle": "Informativa sulla privacy",
  "functionSetting": "Impostazioni delle funzioni",
  "generalSetting": "Impostazioni generali",
  "securitySetting": "Impostazioni di sicurezza",
  "moreSetting": "Impostazioni aggiuntive",
  "locationRobot": "Localizza il mio aspirapolvere/pulisci pavimenti",
  "areaEditTip1": "Si consiglia di regolare le aree in base al layout effettivo della casa.",
  "areaMerge": "Unisci",
  "areaSplit": "Dividi",
  "areaEditTip2": "Seleziona due aree adiacenti da unire",
  "selectOneSplit": "Seleziona un'area da dividere",
  "livingRoom": "Soggiorno",
  "bedRoom": "Camera da letto",
  "kitchen": "Cucina",
  "washingRoom": "Bagno",
  "balcony": "Balcone",
  "disturbTip": "Non può coincidere con l'ora di inizio, imposta nuovamente.",
  "customClean": "Zona",
  "autoClean": "Tutto",
  "undefined": "Pulizia mocio",
  "english": "Inglese",
  "addedAreaNum": "\n{count} stanze selezionate sono state aggiunte",
  "local": "Parziale",
  "selectAreaClean": "Seleziona Pulizia delle stanze",
  "selectArea": "Scegli stanza",
  "selectAreaAfterSmartlearning": "Dopo aver appreso la mappa intelligente, è possibile utilizzare la funzione Pulizia delle stanze selezionata",
  "timezoneTips": "Avete bisogno di sincronizzare il fuso orario.",
  "otaSuccess": "Aggiornamento completato",
  "savedMapUse": "Si prega di usarlo sulle mappe salvate",
  "GuideKeepSweeperTips": "Il scopa aspirante si ricaricherà automaticamente se si scarica durante la pulizia. Riprenderà a pulire l'area non pulita dopo la ricaricata necessaria.",
  "nokeepClean": "Il scopa aspirante non riprenderà la pulizia per il periodo impostato.",
  "keepSweeperOnpened": "La pulizia dal punto di interruzione è stata attivata",
  "nodistrubTipOpened": "La modalità Non Disturbare è stata attivata.",
  "mop": "Rastrellamento",
  "offline": "Disconnesso",
  "upgrading": "Aggiornamento",
  "positioning": "Posizionamento/Localizzazione",
  "cleaningTime": "Tempo di pulizia",
  "totalArea": "Area di pulizia",
  "maploading1": "Rimuovere i capelli bloccati dalla scopa principale in tempo",
  "maploading2": "Il scopa aspirante si spegne automaticamente se lasciato in Modalità di riposo per più di 2 ore",
  "maploading3": "Il filtro può essere pulito con l’acqua e reinserito una volta asciugato.",
  "maploading5": "Il scopa aspirante si avvierà quando sarà messo nel supporto di ricarica.",
  "maploading6": "Togliere gli ostacoli e giochi dal pavimento prima dell’utilizzo.",
  "maploading7": "Pulire tutti i sensori dopo che il scopa aspirante è in uso per un pò di tempo.",
  "maploading8": "Non far allontanare troppo il scopa aspirante durante la pulizia, potrebbe perdersi",
  "dataLoadingErr": "Caricamento dei dati fallito, uscire e riprovare",
  "noMapChangeModeTips": "Utilizzare dopo il completo salvataggio della mappa",
  "selectAreaNumMsg": "Pulire {num} volte",
  "emptyMap": "Nessuna mappa",
  "operateFaild": "Operazione fallita",
  "mergeTipMsg": "Dopo l'unione della zona, i tempi relativi a quella zona non saranno più validi",
  "areaToplimit": "La partizione ha raggiunto il massimo",
  "splitTipMsg": "Dopo la divisone della zona, i tempi relativi a quella zona non saranno più validi",
  "areaNameWithSpeWords": "Il nome della zona non può contenere i caratteri speciali",
  "studyRoom": "Studio",
  "diningRoom": "Sala pranzo",
  "corridor": "Corridoio",
  "sundryRoom": "Ripostiglio",
  "cloakRoom": "Guardaroba",
  "mettingRoom": "Sala ",
  "office": "Ufficio",
  "fitnessArea": "Area fitness",
  "leisureArea": "Area ricreativa",
  "resetAreaMsg": "Verranno eliminate anche le impostazioni relative alla mappa. Continuare?",
  "resetSuccess": "Ripristinato con successo",
  "wifiMap": "Mappa Wi-Fi",
  "mapStrength": "Forte-debole",
  "virtualLine": "Muro virtuale",
  "cleanVirtualRect": "Zona vietata",
  "mopVirtualRect": "Lavaggio della Zona vietata",
  "keepSweeperInfo": "Il scopa aspirante continuerà con le pulizie non finite dopo essere stato ricaricato",
  "chargingWatertankTitle": "Rimuovere il serbatoio dell’acqua prima di ricaricare",
  "chargingWatertankInfo": "Rimuovere il modulo di lavaggio prima di ricaricare. Evitare di bagnare il pavimento.",
  "resetMapTitle2": "Dettagli del messaggio",
  "volume": "Voce e volume",
  "keepSweeperTips": "Dopo l’accensione, il robot si ricaricherà automaticamente se si scarica durante la pulizia. Riprenderà a pulire l'area non pulita dopo la ricaricata necessaria.",
  "carpetCarpet": "Rinforzo dei tappeti",
  "syncFail": "Sincronizzazione fallita",
  "robotVolume": "Volume del scopa aspirante",
  "volumeTip": "Trascina il cursore per regolare e ascoltare il volume della voce del robot",
  "robotVoice": "Voce del robot",
  "downloading": "Scaricamento",
  "downloadFail": "Scaricamento non riuscito",
  "invalidTiming": "La mappa è cambiata, i tempi non è validi",
  "cleanScope": "Raggio di pulizia",
  "drawOrder": "Premere gli Hot spot dell'area per disegnare un ordine di pulizia del scopa aspirante in base ai requisiti di pulizia successivi.",
  "noSelectAreaTip": "Selezionare la zona da pulire",
  "timingAutoRouteTip": "L’ordine di pulizia non impostato, verrà eseguita in ordine predefinito.",
  "timingDrawRouteTip": "Il scopa aspirante pulirà in ordine del percorso disegnato",
  "timingInNoDisturb": "Le pulizie programmate vengono impostate durante la modalità Non disturbare. Continuare?",
  "cleanInfoDetail": "Dettagli della pulizia",
  "cleanStatus": "Stato della pulizia",
  "complete": "Completato",
  "break": "Interrompere",
  "productUsageGuide": "Guida all’uso del prodotto",
  "FAQ": "FAQ",
  "newEnvNewClean": "Nuova posizione rilevata, il scopa aspirante inizierà con la nuova pulizia.",
  "moveBackToDock": "Rimettere il scopa aspirante nel supporto di ricarica e la mappa verrà ripristinata",
  "hotMap": "Mappa di calore",
  "carpetCarpetTips": "Il scopa aspirante dopo avvio riconoscerà automaticamente il tappeto, accenderà l'aspirazione massima e riprenderà automaticamente l'aspirazione normale dopo aver lasciato il tappeto. *Efficace dopo che si è iniziato con la superficie senza tappeti.",
  "customAreaClean": "Pulizia a zone",
  "loading": "Caricamento dati...",
  "fullCleanup": "Pulizia completa",
  "msgSwitch": "Interruttore notifiche",
  "start": "Avvio",
  "end": "Fine",
  "areaType": "Tipo di partizione",
  "usageGuide": "Guida all'uso",
  "cleanMopReminder": "Dopo l'accensione, l'aspirapolvere ricorderà di pulire il panno dopo il tempo impostato",
  "SNMismatch": "Questo modello non è supportato nell'area corrente",
  "startNow": "Avvia ora",
  "cleanTimes": "Tempi di pulizia",
  "mapManage": "Gestione mappe",
  "guideDesc1": "Al termine della pulizia, l'aspirapolvere/lavapavimenti avvia torna automaticamente alla stazione di ricarica. Se riposto manualmente sulla stazione di ricarica, l'aspirapolvere/lavapavimenti non è in grado di apprendere le mappe delle stanze.",
  "guideDesc2": "Puoi utilizzare la funzione di salvataggio delle mappe, dopo averla abilitata nelle funzioni sperimentali.",
  "guideDesc3": "Come faccio a utilizzare la pulizia a zone e la creazione di pareti virtuali?",
  "guideDesc4": "Per fare in modo che il dispositivo apprenda le mappe e per utilizzare la pulizia a zone e la creazione di pareti virtuali, devi attivare la modalità di salvataggio delle mappe da Impostazioni > Funzioni sperimentali.",
  "productDetail": "Dettagli prodotto ",
  "productInstructions": "Manuale Prodotto",
  "nextStep": "Prossimo step",
  "nodisturbTips": "Batteria scarica. Il robot tornerà alla stazione per ricaricarsi automaticamente. Una volta totalmente carico, il robot continuerà a pulire. Per assicurarsi un ambiente di riposo tranquillo, si raccomanda di impostare un periodo in modalità \"non disturbare\".",
  "startExper": "Premi start per iniziare",
  "timingStart": "Apri",
  "noviceStudyTip1": "Modalità silenziosa è indicata per la pulizia in un ambiente tranquillo, con la più bassa rumorosità di aspirazione e una durata più lunga della batteria",
  "noviceStudyTip2": "La modalità standard è indicata per una pulizia in un ambiente ordinario, con una moderata rumorosità di aspirazione e una lunga durata della batteria",
  "raterRegulate": "Regolazione flusso d'acqua",
  "studyMopTip1": "Un flusso d'acqua leggero è indicato per una pulizia su pavimento bagnato ",
  "studyMopTip2": "Un flusso d'acqua medio è indicato per una pulizia generale",
  "studyMopTip3": "Un flusso d'acqua alto è indicato per la pulizia di un pavimento più sporco",
  "majorFunction": "Funzioni principali",
  "studyClean": "Pulizia",
  "studyCharge": "Ricarica",
  "cleanAvoidTips": "Quando il robot è in funzione, evita automaticamente il muro virtuale",
  "restrictedAreaTips": "Il robot non entrerà in quest'area durante le modalità di Aspirazione e Lavaggio",
  "restrictedAreaMopTips": "L'area vietata al lavaggio è inaccessibile al robot solo durante la Modalità Lavaggio",
  "restrictedAreaClean": "Pulizia dell'area vietata",
  "LineCountTips": "Il numero di muri virtuali ha raggiunto il suo limite",
  "cleanRectCountTips": "Il numero di area vietate alla pulizia ha raggiunto il suo limite",
  "mopRectCountTips": "Il numero di aree vietate al lavaggio ha raggiunto il suo limite",
  "save": "Salva",
  "noSave": "Non salvare",
  "splitErr1": "La divisione in zone è inferiore a 1 metro quadrato; divisione fallita",
  "splitErr2": "La fine della linea di divisione non è all'interno dei confini della zona di divisione; divisione fallita",
  "messageList": "Lista suggerimenti comandi",
  "messageTips": "Suggerimenti comandi, visualizza",
  "faultList": "Suggerimenti errori, lista",
  "faultMessageList": "Lista Errore e Messaggio",
  "faultTips": "Suggerimenti errore, gestisci",
  "clothCleanDialog": "Pulizia mocio (solo lavaggio)",
  "cleanMin": "{num}minuti dopo",
  "mapChaged": "Variazione mappa",
  "noComplete": "Non terminato",
  "selectAreaCountMsg": "Aree selezionate: {count}"
};