module.exports = {
  "guideTipTitle1": "가구를 정리해 주세요.",
  "guideTipDesc1": "집 안에 있는 테이블 및 의자 등의 가구를 정돈해 주시고 청소할 면적을 최대한 넓게 만들어 주세요. 또한 청소기가 걸리지 않도록 바닥에 흐트러진 물건들을 정리해 주세요.",
  "guideTipTitle2": "충전 스탠드를 잘 놓아 주세요.",
  "guideTipDesc2": "충전 스탠드 주변에 장애물이 없도록 해 주시고 청소기로 인해 잡아 당겨지지 않도록 전원 케이블 선을 잘 정리해 주세요.",
  "guideTipTitle3": "실내에 적절한 빛을 유지해 주세요.",
  "guideTipDesc3": "청소기가 더욱 수월하게 청소할 수 있도록 청소 구역에 최대한 적절한 빛이 들어올 수 있도록 유지해 주세요.",
  "cleaning": "청소중",
  "pause": "일시 정지",
  "waiting": "대기",
  "charging": "충전 중",
  "gocharging": "반송 요금",
  "completedCharge": "충전 완료 됨",
  "localClean": "부분 청소",
  "strongModeTip": "강력 모드는 카펫 청소 시 사용하는 모드입니다. 흡입력이 강해질수록 소리가 조금 더 커지며 연속 사용 시간도 짧아집니다.",
  "turboModeTip": "슈퍼 강력 모드는 장모 카펫 청소 시 사용하는 모드입니다. 흡입력이 강해질수록 소리가 조금 더 커지며 연속 사용 시간도 짧아집니다.",
  "experimental": "시험 기능",
  "mapsavemode": "지도 저장 모드",
  "mapsavetip": "해당 기능을 켜면 AI 지도가 지속적으로 개선되며 지도를 저장할 수 있고 소프트웨어 적인 가상벽, 금지 구역 등을 설정할 수 있습니다.",
  "SmartLearning": "AI 지도 합습 중...",
  "SmartLearningTip": "서로 다른 빛 환경에서 청소를 여러 번 수행하면 지도가 저장되며 청소 구역 지정, 가상벽 등의 기능을 사용할 수 있습니다.",
  "SmartLearningTip2": "청소 시 집 안에 있는 방문을 모두 열어 전체적인 지도를 완성할 수 있게 하십시오.",
  "saveMapTip1": "청소 상태에서 전원을 끄지 마세요",
  "saveMapTip2": "전원을 끄면 저장된 지도 및 관련 설정이 초기화됩니다.",
  "zonedStopTaskMsg": "해당 조작을 진행할 경우 현재 작업이 중단됩니다. 계속하시겠습니까?",
  "cleanTip": "현재 청소를 종료하고 재충전을 시작하시겠습니까?",
  "customAreaAfterSmartlearning": "AI 지도 학습 완료 후 지정 구역 청소 기능을 사용할 수 있습니다.",
  "customAreaMsg": "지정한 구역 범위를 청소합니다.",
  "areaManage": "구역 편집",
  "reset": "초기화",
  "renameNoSelect": "이름을 바꿀 단일 영역을 선택하십시오",
  "resetFail": "재설정 실패",
  "restricted_area": "금지구역/가상벽",
  "virtualWallPageTips": "금지구역 또는 가상벽으로 위험 구역을 격리할 수 없습니다.",
  "virtualAreaMsg": "현재 설정된 금지 구역 및 가상벽을 저장하겠습니까?",
  "virtualRactCountMsg": "설정 가능한 금지구역/가상벽 수량을 초과하였습니다.",
  "chargerCoveredRect": "충전 스탠드가 있는 구역은 금지 구역을 설정할 수 없습니다.",
  "chargerCoveredLine": "충전 스탠드가 있는 구역은 가상벽을 설정할 수 없습니다.",
  "keepSweeperTitle": "청소 끊긴 지점에서 계속 청소하기",
  "resetMapTitle": "청소 경로가 일치하지 않습니다.",
  "resetMapTip2": "지도를 재설정한 후 밝을 때 모든 영역을 다시 청소하십시오.",
  "reset_map": "지도 재설정",
  "heapWarnTitle1": "필터가 곧 만료됩니다",
  "heapWarnMsg1": "필터가 곧 만료됩니다, 제 때 교체하십시오",
  "heap": "필터",
  "remain": "남음",
  "remainDay": "{hour} 시간 사용 가능 예정",
  "heapDesc": "필터는 먼지가 먼지함에서 밖으로 빠져 나가는 것을 방지하기 위해 폴리머 섬유로 구성됩니다. 작업 시간이 늘어남에 따라 효력이 떨어지게 됩니다. 작업 시간을 {time} 시간 또는 교체 시간을 단축하는 것이 좋습니다.",
  "materialReset": "{name} 재설정",
  "buy": "지금 바로 구입",
  "resetHeapMessage": "새 필터로 교체했습니까?",
  "slidBrushWarnTipTitle1": "사이드 브러쉬가 곧 만료됩니다",
  "slidBrushWarnTipMsg1": "사이드 브러쉬가 곧 만료됩니다, 제 때 교체하십시오",
  "slidBrush": "사이드 브러쉬",
  "slidBrushDesc": "사이드 브러쉬는 코너의 쓰레기를 청소하고 쓰레기를 메인 브러쉬로 보냅니다. 작업 시간이 길어짐에 따라 마모가 발생하며 청소 효과에 영향을 줍니다. 작업 시간을 {time} 시간 또는 교체 시간을 단축하는 것이 좋습니다.",
  "resetSlidBrushMessage": "새 사이드 브러쉬가 교체 되었습니까?",
  "rollingBrushWarnTitle1": "메인 브러쉬가 곧 만료됩니다",
  "rollingBrushWarnMsg1": "메인 브러쉬가 곧 만료됩니다, 제 때 교체하십시오",
  "rollingBrush": "메인 브러쉬",
  "rollingBrushDesc": "메인 브러쉬는 쓰레기를 고속으로 먼지함에 넣는 주요 부품입니다. 메인 브러쉬는 작업 시간이 길어짐에 따라 마모됩니다. 작업 시간을 {time} 시간 또는 교체 시간을 단축하는 것이 좋습니다.",
  "resetRollingBrushMessage": "새 메인 브러쉬가 교체 되었습니까?",
  "heapWarnTitle2": "필터가 만료되었습니다",
  "heapWarnMsg2": "필터가 만료되었습니다, 교체하십시오",
  "slidBrushWarnTipTitle2": "사이드 브러쉬가 만료되었습니다",
  "slidBrushWarnTipMsg2": "사이드 브러쉬가 만료되었습니다, 교체하십시오",
  "rollingBrushWarnTitle2": "메인 브러쉬가 만료되었습니다",
  "rollingBrushWarnMsg2": "메인 브러쉬가 만료되었습니다, 교체하십시오",
  "warnInfoTitle": "오류 세부 정보",
  "morequestion": "질문 더 보기",
  "feedback2": "문제 피드백",
  "setting": "설정",
  "robotSetting": "장치 설정",
  "timeZone": "기기의 표준 시간대",
  "disturbTime": "방해 금지 모드",
  "nodistrubTip": "전원을 켜면 설정한 시간 내에 스위프가 자동으로 재개되지 않습니다. 예정된 약속 작업은 설정된 방해 금지 시간대 동안 작동됩니다.",
  "timezoneTip1": "스마트폰의 표준 시간대를 장치와 동기화할 수 있습니다, 휴대 전화와 장치가 동일한 시간대에 있는지 확인하십시오",
  "timezoneTip2": "* 장치의표준 시간대가 정확하지 않습니다, 타이밍 청소 및 방해 금지 모드 시간 오류를 유발할 수 있습니다",
  "syncTimeZone": "지금 동기화",
  "syncSuccess": "동기화 완료",
  "famaleVoice": "클래식 여성 사운드",
  "used": "흐름",
  "use": "사용",
  "cleanTiming": "시간 설정",
  "noTiming": "설정된 타이머가 없습니다",
  "once": "한 번 작동",
  "Monday": "월요일",
  "Tuesday": "화요일",
  "Wednesday": "수요일",
  "Thursday": "목요일",
  "Friday": "금요일",
  "Saturday": "토요일",
  "Sunday": "일요일",
  "workDay": "근무일(월요일부터 금요일)",
  "weekend": "주말",
  "everyDay": "매일",
  "modeQuiet": "저소음 모드",
  "modeStandard": "일반 모드",
  "modeMedium": "강력",
  "modeStrong": "강력 모드",
  "low": "낮음",
  "middle": "보통",
  "high": "높음",
  "startTime": "작동 시간",
  "repeat": "반복",
  "cleanMode": "청소 모드",
  "waterVolume": "물 수위 설정",
  "sure": "확인",
  "cancle": "취소",
  "deleteMsg": "이 타이머 설정을 삭제합니다",
  "networkTimeout": "지정된 요청 시간을 초과하였습니다",
  "timingNumTip": "예약 작업이 상한에 도달하여 작업을 추가할 수 없습니다",
  "cleanLog": "청소 기록",
  "totalTime": "누적 기간",
  "totalAreas": "누적 면적",
  "totalTimes": "누적 횟수",
  "emptyLog": "레코드가 비어 있습니다",
  "materialTime": "소모품 카운트",
  "brushExpireDesc": "{time} 시간후에 교체 할 것으로 예상됩니다",
  "Instructions": "사용 설명",
  "otatitle": "펌웨어 업데이트 확인",
  "otaChecking": "테스트 중...",
  "currentVersion": "현재 버전",
  "latestVersion": "최신 버전",
  "isLatestVersion": "현재 최신 버전입니다",
  "checkVersionFailed": "업데이트할 수 있는 펌웨어 감지에 실패했습니다",
  "retry": "다시 시도",
  "updateNow": "업그레이드",
  "updateTip": "업그레이드하기 전에 충전 도크에 장치를 놓고 배터리 레벨을 15 % 이상으로 유지하십시오",
  "upgradeErr": "업그레이드 실패",
  "updating": "업그레이드 중...",
  "updateTip2": "업그레이드하는 동안 전원을 끄지 말고 사용하기 전에 업그레이드가 완료 될 때까지 기다리십시오",
  "installing": "업데이트 설치중...",
  "installtip": "설치 과정에서 기기를 다시 부팅해야 하므로 오래 걸릴 수 있습니다, 잠시 기다려주십시오",
  "updatesuccess": "업데이트 완료",
  "upgradeErr1": "펌웨어 다운로드 실패",
  "upgradeErr5": "펌웨어 업데이트 실패",
  "upgradeErr8": "본체가 충전 중이 아니므로 업그레이드 할 수 없습니다",
  "upgradeErr7": "배터리가 부족합니다, 업그레이드 할 수 없습니다",
  "updateDialogTip": "장치에 최신 펌웨어 버전이 {count}인 것으로 감지되었습니다, 업그레이드하시겠습니까？",
  "forceTitle": "새로운 펌웨어 버전이 있습니다.",
  "productGuide": "도움말 사용",
  "deleteDevice": "기기 삭제",
  "deveiceName": "기기 이름",
  "deviceShare": "기기 공유",
  "locationManager": "위치 관리",
  "otaCheck": "펌웨어 업그레이드",
  "addDesktop": "바탕 화면 바로 가기 추가",
  "feedback": "문제 피드백",
  "useTerms": "법률 정보",
  "licenseTitle": "사용자 약관 정보",
  "policyTitle": "개인 정보 보호 정책",
  "functionSetting": "기능 설정",
  "generalSetting": "일반 설정",
  "securitySetting": "보안 설정",
  "moreSetting": "추가 설정",
  "locationRobot": "내 기기 위치 지정",
  "areaEditTip1": "실제 실내 구조에 따라 영역을 조정하는 것이 좋습니다",
  "areaMerge": "합병",
  "areaSplit": "분할",
  "areaEditTip2": "병합할 인접한 두 개의 인접한 영역을 선택하십시오",
  "selectOneSplit": "분할할 영역을 선택하십시오",
  "livingRoom": "거실",
  "bedRoom": "침실",
  "kitchen": "주방",
  "washingRoom": "화장실",
  "balcony": "발코니",
  "disturbTip": "설정된 시작 시간이 동일합니다, 다시 설정하십시오",
  "customClean": "구역",
  "autoClean": "모든/전부",
  "undefined": "걸레 세척",
  "english": "영문",
  "addedAreaNum": "선택하신 {count} 개의 구역이 추가되었습니다.",
  "local": "일부/부분",
  "selectAreaClean": "선택한 방 청소",
  "selectArea": "방",
  "selectAreaAfterSmartlearning": "스마트맵 설정 후, 선택 방 청소 기능을 사용할 수 있습니다.",
  "timezoneTips": "표준시간대를 동기화 하시겠습니까?",
  "otaSuccess": "업데이트가 완료되었습니다.",
  "savedMapUse": "저장된 지도에 사용하십시오.",
  "GuideKeepSweeperTips": "청소 중에 전력이 부족하면 진공청소기가 자동으로 재충전됩니다. 진공청소기에 적절한 전원이 공급 된 후 청소되지 않은 부분을 계속 청소합니다.",
  "nokeepClean": "이 진공청소기는 설정하는 동안 청소 기능을 수행할 수 없습니다.",
  "keepSweeperOnpened": "중단 계속 청소 모드가 켜져 있습니다",
  "nodistrubTipOpened": "방해 금지 모드가 켜져 있습니다",
  "mop": "닦는 중입니다.",
  "upgrading": "업데이트 중입니다.",
  "positioning": "포지셔닝 / 위치 확인중",
  "cleaningTime": "청소 시간",
  "maploading1": "메인 브러시에 얽힌 머리카락을 제때에 제거하십시오",
  "maploading2": "휴면 모드에서 2 시간 이상 방치하면 진공청소기가 자동으로 종료됩니다.",
  "maploading3": "필터는 물로 세척하고 건조 후 다시 설치할 수 있습니다.",
  "maploading5": "진공청소기는 충전기에 직접 놓이면 켜집니다.",
  "maploading6": "사용하기 전에 바닥에서 코드와 장난감을 제거하십시오",
  "maploading7": "진공청소기가 잠시 작동 한 후 모든 센서를 깨끗하게 닦으십시오",
  "maploading8": "진공청소기가 청소하는 동안 멀리 있는 곳에 옮겨두지 마십시오. 길을 잃을 수도 있습니다.",
  "dataLoadingErr": "데이터 로드에 실패했습니다. 종료한 후 다시 시도하십시오",
  "noMapChangeModeTips": "맵이 완성 된 후 사용하십시오",
  "selectAreaNumMsg": "{num}회 청소",
  "emptyMap": "맵이 없습니다",
  "operateFaild": "작업 실패",
  "mergeTipMsg": "영역이 병합되면 해당 영역과 관련된 타이밍이 유효하지 않습니다",
  "areaToplimit": "영역이 최대치로 분할 되었습니다.",
  "splitTipMsg": "영역이 분할되면 해당 영역과 관련된 타이밍이 유효하지 않습니다",
  "areaNameWithSpeWords": "지역 이름은 특수 문자를 포함할 수 없습니다",
  "studyRoom": "서재",
  "diningRoom": "식당",
  "corridor": "복도",
  "sundryRoom": "다용도실",
  "cloakRoom": "드레스룸",
  "mettingRoom": "객실",
  "office": "사무실",
  "fitnessArea": "피트니스 공간",
  "leisureArea": "레크레이션 구역",
  "resetAreaMsg": "맵 관련 설정도 삭제됩니다. 계속하겠습니까?",
  "resetSuccess": "재설정 완료",
  "wifiMap": "와이파이 지도",
  "mapStrength": "강-약",
  "virtualLine": "가상 벽",
  "cleanVirtualRect": "접근금지 구역",
  "mopVirtualRect": "청소 금지 구역",
  "keepSweeperInfo": "충전 후 진공청소기는 완료되지 않은 청소 작업을 계속 수행합니다",
  "chargingWatertankTitle": "충전하기 전에 물 탱크를 제거하십시오",
  "chargingWatertankInfo": "충전하기 전에 걸레질 모듈을 제거하십시오. 젖은 걸레로 바닥을 적시 지 마십시오.",
  "resetMapTitle2": "메시지 세부 사항",
  "volume": "음성 및 볼륨",
  "keepSweeperTips": "전원을 켠 후 청소 중에 전원이 부족하면 진공청소기가 자동으로 재충전됩니다. 진공청소기는 적절한 전원이 공급 된 후 청소되지 않은 구역을 계속 청소합니다.",
  "carpetCarpet": "카펫 부스터",
  "syncFail": "동기화 실패",
  "robotVolume": "진공청소기 음량",
  "volumeTip": "슬라이더를 드래그하여 진공청소기 음성 볼륨을 조정하고 들으십시오",
  "robotVoice": "진공청소기 음성",
  "downloading": "다운로드 중",
  "downloadFail": "다운로드 실패",
  "invalidTiming": "맵이 변경되었고 타이밍이 잘못되었습니다",
  "cleanScope": "청소 범위",
  "drawOrder": "연속적인 청소 요구 사항에 따라 진공청소기의 청소 순서를 그리려면 영역의 핫스팟을 누르십시오.",
  "noSelectAreaTip": "청소 구역을 선택하십시오",
  "timingAutoRouteTip": "청소 주문을 추가하지 않은 경우 기본 설정 순서대로 수행됩니다",
  "timingDrawRouteTip": "진공청소기는 그려진 경로의 순서대로 청소합니다",
  "timingInNoDisturb": "예약 된 청소 작업은 방해 금지 기간 동안 설정됩니다. 계속하겠습니까?",
  "cleanInfoDetail": "청소 세부 사항",
  "cleanStatus": "청소 상태",
  "complete": "완성",
  "break": "멈춤",
  "productUsageGuide": "제품 사용 지침서",
  "FAQ": "자주하는 질문",
  "newEnvNewClean": "새로운 위치가 감지되면 진공청소기가 새로운 청소 작업을 시작합니다.",
  "moveBackToDock": "진공청소기를 충전 장소로 옮기면 지도가 복원됩니다.",
  "hotMap": "적외선 열 지도",
  "carpetCarpetTips": "전원을 켜면 진공청소기가 카펫을 자동으로 인식하고 최대 흡입으로 설정하고 카펫을 떠난 후 자동으로 일반 흡입을 재개합니다. * 카펫이 아닌 곳에서 작업을 시작한 후에 효과적입니다.",
  "customAreaClean": "구역 청소",
  "loading": "데이터 로드 중...",
  "fullCleanup": "전체 영역 청소",
  "msgSwitch": "메시지 알림 스위치",
  "start": "시작",
  "end": "종료",
  "areaType": "파티션 유형",
  "usageGuide": "이용 가이드",
  "cleanMopReminder": "전원이 켜진 후, 정해진 시간이 지나면 진공청소기에서 걸레를 청소하라는 알람이 울립니다.",
  "SNMismatch": "이 모델은 현재 구역에서 지원되지\n않습니다.",
  "startNow": "지금 시작",
  "cleanTimes": "청소 횟수",
  "mapManage": "지도 관리",
  "guideDesc1": "청소 후 호스트가 충전 스탠드에 자동으로 돌아가도록 하십시오. 수동으로 돌아가서 충전을 설정하거나 호스트를 충전 스탠드로 옮기면 지도를 학습할 수 없습니다.",
  "guideDesc2": "실험 기능에서 “지도 저장 모드”를 켠 후 지도 기능을 사용할 수 있습니다.",
  "guideDesc3": "구역 청소 및 가상 벽 기능은 어떻게 사용하나요?",
  "guideDesc4": "설정>실험실 기능 중 “지도 저장 모드”를 켠 후 지도 학습에 성공하면 구역 청소 및 가상 벽 기능을 사용할 수 있습니다.",
  "productDetail": "제품 상세",
  "productInstructions": "제품설명서",
  "nextStep": "다음 단계",
  "nodisturbTips": "본체의 전력이 부족하면 자동으로 충전덱에 돌아가며, 충전이 완료되면 나머지 작업을 진행합니다. 수면에 방해되지 않도록 설정 시간을 조정해 주세요.",
  "startExper": "체험 시작",
  "timingStart": "시작",
  "noviceStudyTip1": "저소음 모드는 조용한 환경에서의 청소에 최적화 되어 있으며, 흡입 시 소음이 가장 적고 사용 시간 역시 가장 깁니다.",
  "noviceStudyTip2": "표준 모드는 일반적인 환경에서의 청소에 최적화 되어 있으며, 흡입 시 소음이 비교적 적으며, 사용 시간도 비교적 깁니다.",
  "raterRegulate": "물양 조절",
  "studyMopTip1": "낮은 물 양은 젖은 바닥을 닦는 데 적합합니다.",
  "studyMopTip2": "중간 정도의 물 양은 일반적인 청소에 적합합니다.",
  "studyMopTip3": "높은 정도의 물 양은 오염된 바닥 청소에 적합합니다.",
  "majorFunction": "주요 기능",
  "studyClean": "청소",
  "studyCharge": "충전 모드",
  "cleanAvoidTips": "본체가 청소 중일 때, 자동으로 가상 벽 구획을 피하여 청소합니다.",
  "restrictedAreaTips": "청소 모드에서는 본체가 해당 구역에 진입하지 않습니다.",
  "restrictedAreaMopTips": "걸레질 금지 구역은 단지 걸레질 모드 수행 시 본체가 해당 구역에 진입하지 않는 것을 의미합니다.",
  "restrictedAreaClean": "청소 금지 구역",
  "LineCountTips": "설정 횟수 초과로 더 이상 가상 벽을 설정할 수 없습니다.",
  "cleanRectCountTips": "설정 횟수 초과로 더 이상 청소 금지 구역을 설정할 수 없습니다.",
  "mopRectCountTips": "설정 횟수 초과로 더 이상 걸레질 금지 구역을 설정할 수 없습니다.",
  "save": "저장",
  "noSave": "저장하지 않음",
  "splitErr1": "분할 구역이 1제곱미터보다 작아, 분할에 실패하였습니다.",
  "splitErr2": "분할선의 끝점이 분할 영역 경계에 있지 않아, 분할에 실패하였습니다.",
  "messageList": "도움말 목록",
  "messageTips": "도움말 목록을 살펴 보십시오.",
  "faultList": "고장 알림 목록",
  "faultMessageList": "고장 및 도움말 목록",
  "faultTips": "고장 알림, 해결이 필요합니다.",
  "clothCleanDialog": "걸레 세척(걸레질 할 때)",
  "cleanMin": "{num}분일 때",
  "mapChaged": "지도가 변경되어",
  "noComplete": "완료되지 않았습니다.",
  "selectAreaCountMsg": "{count} 개 구역 선택"
};